### ISSUE TITLE
Improve UX with `balena deploy` when pushing an identical image

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1045]
Create a new release object rather than re-uploading the image entirely

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fuxf)

**Comment by dfunckt** [comment]
To flesh this out some more, the CLI does create a new release but *also* re-uploads the complete image, and that is the issue here really. #1057 improved this so repeated invocations of `balena deploy` benefit from cross-repo mounts and no blobs are uploaded.

What still does not work however, is doing the equivalent of `balena deploy; docker rmi <built image>; balena deploy`. In this case the full image is pushed again, because of the requirement for the engine to explicitly instruct the registry which repo it should mount layers from -- it simply doesn't know of the previous images because they've been removed locally.

The first case is typically the workflow of a developer doing work on their laptop and deploying. The latter may be the case if the CLI is naively integrated in a CI pipeline, where there's build, deploy and finally cleanup.

To fix the latter case, `balena deploy` should pull the previous release images first thing, which can also serve as a build cache, like on the cloud builder. This will add a tiny bit of redundant overhead in the first case (for the CLI to get a token and pull the image, which should result in zero bytes downloaded), which is acceptable.

cc @pdcastro @srlowe

**Comment by pdcastro** [comment]
Closing this issue as I understand that the feature was delivered by @xginn8 's PR #1057 of Dec 2018 - CLI v9.9.0. Furthermore, PR #1848 proved to be of no additional benefit.
