### ISSUE TITLE
Can not SSH to device

### ISSUE THREAD

**Issue by richardlevano** [balena-io/balena-cli#1058]
- **Cli version:** 9.7.0
- **Standalone install:** no
- **Node version:** 8.11.4
- **Npm version:** 6.5.0
- **Operating system and architecture:** Linux Ubuntu 18.04.1 LTS

>$ balena device 79a1dd9
== HIDDEN SKY
ID:                 8
DEVICE TYPE:        imx6ul-var-dart
STATUS:             idle
IS ONLINE:          true
APPLICATION NAME:   imx6ulApp
UUID:               79a1dd9c1bacdc79661d1afd31e7c52b
COMMIT:             fc2e2716d8c8913ae434a0f05f9ed713
SUPERVISOR VERSION: 8.6.3
OS VERSION:         balenaOS 2.28.0+rev2
DASHBOARD URL:      https://dashboard.mydomain.com/devices/79a1dd9c1bacdc79661d1afd31e7c52b/summary

But when :  

>$ balena ssh 79a1dd9
Connecting to: 79a1dd9
BalenaRequestError: Request error: tunneling socket could not be established, cause=connect ECONNREFUSED 172.18.0.6:3128

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by pdcastro** [comment]
@richardlevano, it looks like this issue fell through the cracks, and no one replied to it at the time -- sorry for that. Since then, CLI v11 was released (currently v11.18.2) and substantial changes were made to the `balena ssh` command. I've just tested `balena ssh <uuid>` on macOS, and it worked. I am closing this issue on the assumption it is obsolete by now. If it should not be closed, just add a comment and I will reopen it and investigate it further.
