### ISSUE TITLE
User would like to set tag when using balena deploy

### ISSUE THREAD

**Issue by ZubairLK** [balena-io/balena-cli#1060]
It would be nice to be able to use `balena deploy` and set the tag for the release.

There doesn't seem to be any easy (documented) way to get the release id after a deploy either.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gbzv)

**Comment by blechatellier** [comment]
@ZubairLK thanks, fyi at the moment I'm using awk to parse the output for the commit hash `awk '/^\[Success\] Release: / {print $3}')` - would be great to at least expose the release id in the logs so I can parse them.

**Comment by thgreasi** [comment]
Cross-posting @blechatellier 's suggestion so that we don't lose it
> I was thinking about something like --buildArg, ie: --releaseTag foo=bar

**Comment by pdcastro** [comment]
Related to #892 and #1510

**Comment by thgreasi** [comment]
Keep in mind that since v11.15.0 the CLI does support setting tags using the commit hash.
So if the user can grep that from the `balena deploy` output, then they can use it to do a subsequent `balena tag set mytag --release <commit_hash>`.

This is just a workaround though and doesn't resolve this issue.

See: https://github.com/balena-io/balena-cli/pull/1470

**Comment by mbalamat** [comment]
The `--release-tag` flag was introduced in CLI release v12.38.0.
