### ISSUE TITLE
balena ssh Request error: App not found

### ISSUE THREAD

**Issue by jacobrosenthal** [balena-io/balena-cli#1120]
Cant seem to connect to ssh to a device all of a sudden

- **Cli version:**
9.12.3
- **Standalone install:** yes/no
yes?
- **Node version:**
v11.9.0
- **Npm version:**
6.5.0
- **Operating system and architecture:**
macOS high sierra 10.13.6 (17G5019

---
```
$ sudo balena ssh x.x.x.x
Password:
? Select a device purple-shape (xxxxxxx)
Connecting to: xxxxxxxxxxxxxxxxxxxxxxxxxx
BalenaRequestError: Request error: App not found

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io
$
```

**Comment by pdcastro** [comment]
@jacobrosenthal, it looks like no one replied to this issue - sorry. Since then, CLI v11 was released (currently v11.18.2) and substantial changes were made to the `balena ssh` command. I've just tested `balena ssh x.x.x.x` on a local device with CLI v11.18.2 and it worked. I am closing this issue on the assumption it is obsolete. But if you're still facing issues, just reply / add a comment and I will reopen and investigate it further.

For future reference, the balena support team does not monitor this Github repo, which is used by CLI developers to track issues they're working on. The support team however monitors the forum threads: https://forums.balena.io/c/balena-cloud , so by creating a forum thread you're more likely to get a timely response.
