### ISSUE TITLE
balena sync fails when ssh password requested

### ISSUE THREAD

**Issue by mdtusz** [balena-io/balena-cli#1127]
- **Cli version:** 9.14.2
- **Standalone install:** uhhh? I guess. It's globally installed. 
- **Node version:** 11.10.1
- **Npm version:** 6.8.0
- **Operating system and architecture:** linux 

When using `balena sync`, the command will fail if the ssh password is prompted for. The current workaround I've found is to use `balena sync -v` then watch for the prompt in the waterfall of stdout.

**Comment by pdcastro** [comment]
A bit of a late reply... But instead of further developing the `balena sync` command, the team focused on the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) released in CLI v11. The `balena sync` command was replaced with `balena push <ip-address>`. The documentation around deployment was also much improved earlier this year: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/).
