### ISSUE TITLE
version mismatch of Balena CLI

### ISSUE THREAD

**Issue by krishnageethika** [balena-io/balena-cli#1144]
- **Cli version:**
- **Standalone install:** yes/no
- **Node version:**
- **Npm version:**
- **Operating system and architecture:**

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by krishnageethika** [comment]
Even I have installed the CLI with required node and python versions I am facing the issue of version mismatch. My requirement is high pripority please pull me out of this

**Comment by pdcastro** [comment]
@krishnageethika, I recommend you try the standalone installation (instead of `npm`), as it tends to be more straightforward. Check the standalone installation instructions on this page: https://www.balena.io/docs/reference/cli/#standalone-install

It it still doesn't work, then please provide some more details about the problem:
* A copy-and-paste of the commands you are running, and the resulting output and error messages.
* Operating system (Linux / Mac / Windows and OS version)
* Output of `npm --version`
* Output of `node --version`

For future reference, as this sounds like an installation issue rather than a bug in the CLI, I recommend raising it in the balenaCloud forums instead of GitHub: https://forums.balena.io/c/balena-cloud
Thanks!

**Comment by krishnageethika** [comment]
I am getting the below error:

module version mismatch. Expected 48, got 64.

Additional information may be available in debug mode. Prefix the command
line with DEBUG=1, i.e.: DEBUG=1 balena ...


when I am running the command---sudo balena local configure ~/Downloads/balena.img 

I have followed the same docs as well.
Thank You.

**Comment by pdcastro** [comment]
@krishnageethika, have you have installed the CLI through `npm`, or through the standalone installation method? I recommend you try the standalone installation method, because it comes with pre-compiled binary modules and a matching version of node.

**Comment by pdcastro** [comment]
@krishnageethika, I believe what's is happening in your case is that the modules in the `node_modules` subdirectory of the `balena-cli` installation folder were compiled with a different version of `node` than the version you are now using to run the CLI.

One way of avoiding this problem is to use the standalone installation packages, as they come with pre-compile modules and a matching version of `node`.

If you would instead prefer to use `npm`, you could try to fix the mismatching versions by reinstalling the CLI with the commands:
```
npm uninstall balena-cli -g
npm install balena-cli -g --production --unsafe-perm
```
Depending on your environment, you may need to prefix these commands with `sudo`.

**Comment by krishnageethika** [comment]
@pdcastro  Thank you so much for your support I have used the standalone installation packages only. Will remove everything and try again.

I had another doubt hope you resolve it. Is it necessary to connect the raspberry device only to the system in which I have installed Balena CLI.

Thank you so much for your quick reply.

**Comment by krishnageethika** [comment]
> @pdcastro Thank you so much for your support I have used the standalone installation packages only. Will remove everything and try again.
> 
> I had another doubt hope you resolve it. Is it necessary to connect the raspberry device only to the system in which I have installed Balena CLI.
> 
> Thank you so much for your quick reply.

@pdcastro  could you please help me out of this

**Comment by pdcastro** [comment]
@krishnageethika, it is not necessary to connect a device (such as a Raspberry Pi) directly to the machine where the balena CLI is running. Some commands, such as `balena local scan`, expect the device to be connected to the same local network (e.g. same WiFi SSID or local Ethernet switch).

If you have further support questions, please raise them in the balenaCloud forums: https://forums.balena.io/c/balena-cloud
because we use GitHub for tracking feature requests or bugs. Thanks!

**Comment by krishnageethika** [comment]
> @krishnageethika, it is not necessary to connect a device (such as a Raspberry Pi) directly to the machine where the balena CLI is running. Some commands, such as `balena local scan`, expect the device to be connected to the same local network (e.g. same WiFi SSID or local Ethernet switch).
> 
> If you have further support questions, please raise them in the balenaCloud forums: https://forums.balena.io/c/balena-cloud
> because we use GitHub for tracking feature requests or bugs. Thanks!

Thank You.
