### ISSUE TITLE
support ssh port forwarding

### ISSUE THREAD

**Issue by magiconair** [balena-io/balena-cli#1155]
balena-cli should support ssh port forwarding. This is useful for debugging and accessing non-http protocols on devices connected to an IoT device, e.g. for accessing a binary TCP protocol server. The ssh session should be routed through the same tunnel as the ssh connection itself.

I've asked in the forums but did not get a response so far: https://forums.balena.io/t/ssh-port-forwarding/5772

In case security is an issue for not providing this feature I can say that it took me roughly one hour to write a tcp-websocket-tcp proxy that uses the websocket feature of the public URL to simulate this. This works but is a kludge.

**Comment by magiconair** [comment]
Forget this. Just discovered `balena tunnel`

**Comment by magiconair** [comment]
Actually not, since I can only open a tunnel to listening ports on the balena device itself. What I'm after is `ssh -L 1111:1.2.3.4:5678 uuid.ssh.balena.io` which would map my local port `1111` to `1.2.3.4:5678` via the balena device `uuid`.

**Comment by pdcastro** [comment]
The standard `ssh` and `scp` tools can be used with balenaOS devices, including standard ssh port forwarding. It works with both [development and production balenaOS images](https://www.balena.io/docs/reference/OS/overview/2.x/#dev-vs-prod-images). In the case of a production balenaOS image, a ssh key should be added to the `config.json` file -- see [sshKeys section of the meta-balena README file](https://github.com/balena-os/meta-balena/blob/master/README.md#sshkeys).

The ssh server on a device listens on TCP port number 22222. This port is not blocked by the device host OS, not even in production. If this port is blocked by a firewall or router on the device's local network, the `balena tunnel` command can be used as in the examples below.

Example 1 (port 22222 not blocked in the device's local network)
```
# all commands below to be run your laptop/desktop computer

ssh -L 1111:www.google.com:443 -p 22222 root@<deviceIpAddressOrHostname>
curl -ik https://127.0.0.1:1111
```
In the example above, the `ssh` command connects to the balenaOS device (ssh server on port 22222). It also opens a listening socket on port 1111 on your laptop/desktop computer. When `curl` opens a connection to `127.0.0.1:1111`, the data is tunnelled to the balenaOS device. The device opens a connection to `www.google.com:443` "on demand", and traffic is forwarded between Google and `curl` on your laptop/desktop **via** the balenaOS device.

Example 2 (port 22222 is blocked in the device's local network)
```
# all commands below to be run your laptop/desktop computer

balena tunnel <deviceUUID> -p 22222:4321
ssh -L 1111:www.google.com:443 -p 4321 root@127.0.0.1
curl -ik https://127.0.0.1:1111
```
The `balena tunnel` command above is used to create a tunnel between port 22222 on the balenaOS device (the port that the ssh server listens on) and port 4321 on your laptop/desktop computer. What follows is similar to example 1, except that, instead of `ssh` connecting directly to the device's IP address or hostname, `ssh` connects to port 4321 on the laptop/desktop, which is tunnelled to the device's ssh server. The rest is the same as in the first example.

**Comment by magiconair** [comment]
Thanks @pdcastro . I'll try this tomorrow.

**Comment by magiconair** [comment]
@pdcastro that does not work for me

```
$ balena tunnel xxx -p 22222:4321
[Info]    Tunnel to xxx
[Info]     - tunnelling localhost:4321 to device:22222
[Info]    Waiting for connections...
[Error]   127.0.0.1:50480 => 127.0.0.1:4321 ===> 10.240.0.215:22222 :: Unable to connect: 404 Not Found

# terminal 2
$ ssh -L 1111:www.google.com:443 -p 4321 root@127.0.0.1
ssh_exchange_identification: Connection closed by remote host
```

`balena ssh xxx -s` works

**Comment by pdcastro** [comment]
@magiconair, some suggestions and questions:
* Add the `-v` flag (verbose) to the ssh command, in case the output gives us additional clues:
`ssh -v -L 1111:www.google.com:443 -p 4321 root@127.0.0.1`
* Is the device running a [development or production balenaOS image](https://www.balena.io/docs/reference/OS/overview/2.x/#dev-vs-prod-images)? If it's a development image, we can rule out ssh authentication issues. If it's a production image, it requires public key authentication. (I am not sure whether the `ssh_exchange_identification` error indicates an authentication issue.)
* Ty leaving out the `-L` flag to see if the error changes. I suspect it won't, but it's very easy to try:
`ssh -v -p 4321 root@127.0.0.1`
* The `Unable to connect: 404 Not Found` error sounds like something going wrong on the device itself, as if perhaps the ssh daemon could not be reached through port 22222. @richbayliss, any thoughts about what else it might mean?
  * @magiconair, as you've mentioned that `balena ssh xxx -s` works, try opening a terminal with that command (i.e. to the device's host OS) and then run `netstat -ant`. I would expect one of the output lines to show that the ssh daemon is listening on port 22222:
`tcp        0      0 :::22222                :::*                    LISTEN`

**Comment by magiconair** [comment]
It is listening on :22222 (checked with netstat) and key auth works b/c ssh to the host works. I’ll check the rest later. 

—
Frank Schröder

**Comment by pdcastro** [comment]
@magiconair, FYI, someone else reported the same errors through the balenaCloud forum and I have created a specific CLI issue to track it:
https://github.com/balena-io/balena-cli/issues/1173 _`balena tunnel` fails with "Unable to connect: 404 Not Found" (ssh_exchange_identification)_

So far we have not been able to reproduce the errors.

**Comment by magiconair** [comment]
With the latest balena CLI this works. Also helpful to use github.com/balena-io-playground/ssh-key-insert to install ssh keys on a fleet of devices.

**Comment by pdcastro** [comment]
Closing this issue as I understand that the `balena tunnel` command provides the required functionality, and in some cases it is also possible to use the standard `ssh` command (as described in one of my previous comments above), possibly in combination with the [ssh-key-insert](https://github.com/balena-io-playground/ssh-key-insert) tool to add ssh keys to a fleet.
If you find that this issue should be reopened, just leave a comment.
