### ISSUE TITLE
balena deploy using .gitignore values

### ISSUE THREAD

**Issue by kameshsampath** [balena-io/balena-cli#1157]
- **Cli version:** 10.0.0
- **Standalone install:** no
- **Node version:**v10.15.3
- **Npm version:** 6.7.0
- **Operating system and architecture:** macOS 

---

When doing `balena deploy appName --logs --build ` from the local directory that has `Dockerfile`. The docker files fails to copy from the folder that are ignored via`.gitingore`. IMHO balena deploy should consider only `.dockerignore`

**Comment by pdcastro** [comment]
Valid issue and indeed a popular request (thanks for reporting it!), but I am closing it as it will be handled under another issue that attracted many user comments and is now high up in priority in the backlog: #1032 [Revisit .gitignore file treatment by balena build / balena push](https://github.com/balena-io/balena-cli/issues/1032)

The conclusion under that issue was the same as yours here: that only the `.dockerignore` file should be considered, not `.gitignore`. The balena `push`, `build` and `deploy` commands all share the same "ignore" file treatment, and will be changed at the same time.
