### ISSUE TITLE
Developer needs to enable device local mode with CLI

### ISSUE THREAD

**Issue by roman-mazur** [balena-io/balena-cli#1304]
- **Cli version:** 11.1.0
- **Standalone install:** no, native installer
- **Node version:** 12.4.0
- **Npm version:** 6.9.0
- **Operating system and architecture:** MacOS, x86_64

It currently does not seem to be possible to enable local mode from the command line.

**Comment by tobyhijzen** [comment]
I would like to have this too

**Comment by thgreasi** [comment]
Let me open an SDK issue for this.
See: https://github.com/balena-io/balena-sdk/issues/732

**Comment by thgreasi** [comment]
The related local mode methods are now available in the balena-sdk v9.10.0 .

**Comment by hedss** [comment]
@thgreasi Awesome, great work! I'm writing masterclass tutorials atm. We really, really do need this in and I'd like to prioritise it at the next CLI checkin. cc @shaunmulligan

**Comment by pdcastro** [comment]
We've discussed this issue in today's CLI check-in and I just wanted to leave a comment on what we agreed the command could look like:
```
balena device config local-mode enable/disable <UUID>
```
So we would introduce a `device config` command that sets configuration options such as `local-mode` or `public-url` to values such as `enable` or `disable`. At the same time, we agreed we should migrate the `device public-url` command to the config form:
```
balena device config public-url enable/disable/status <UUID>
```
... and add a deprecation message to the the old `device public-url` form.

**Comment by srlowe** [comment]
@pdcastro Regarding the suggestion above (`balena device config local-mode enable/disable <UUID>`)...

It seem oclif doesn't support this 'depth' of command, ie. `balena <topic> <suptopic> <command>` (I tested). I'm not sure how much work it would be to support that, but given that we have already hacked the framework to support spaces instead of colons, it's probably not a good idea to hack it further.

`balena device-config local-mode enable/disable <UUID>` is an option, but doesn't seem very nice.

Another option would be for `balena device config` to be a kind of supercommand (that accepts a command param, e.g. `local-mode`)

**Comment by pdcastro** [comment]
> Another option would be for balena device config to be a kind of supercommand (that accepts a command param, e.g. local-mode)

@srlowe, I think this supercommand option is reasonable, not by patching oclif but by coding our own trivial parser of the first two positional arguments (`if (params.cmd === 'local-mode') ...`). So `device config` is the oclif command, while `local-mode` and `enable` are positional arguments to `device config`.

**Comment by srlowe** [comment]
@pdcastro Given the recent discussions about autogeneration, I think the supercommand approach would be a mistake, since it bypasses the framework, and forces us to manage multiple commands in the logic of one real command.

**Comment by pdcastro** [comment]
> Given the recent discussions about autogeneration, I think the supercommand approach would be a mistake, since it bypasses the framework, and forces us to manage multiple commands in the logic of one real command.

Yep! I think we should stop manually adding new commands the way we have been doing so far, in favour of an autogeneration approach. It may require first sorting autogeneration of the balena SDK, and it may also require changing the data model all the way up (SBVR, Abstract SQL, balena API, balena SKD, and only then balena CLI) so that the data model matches the needs of autogeneration, but if that's what it takes, that's what we should do. This discussion is bigger than this GitHub issue though, so let's continue it elsewhere. :-)

**Comment by roman-mazur** [comment]
great to see this :)
