### ISSUE TITLE
Balena push <appname>

### ISSUE THREAD

**Issue by pcasey92** [balena-io/balena-cli#1311]
I am doing the Balena Screenly project and am up to the point where I am pushing the code onto my application and I am hit with [Error]Could not detect project type: Resolution could not be performed [Error] Not Deploying release.
I'm unsure as to what is holding it up. I've included a small snip from it to show.

- **Cli version:**
- **Standalone install:** yes/no
- **Node version:**
- **Npm version:**
- **Operating system and architecture:**

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*
![Capture](https://user-images.githubusercontent.com/51840199/59544278-1b14bc00-8ed6-11e9-89c9-59dd49446472.PNG)

**Comment by pdcastro** [comment]
@pcasey92, the screenshot was helpful :-)  It looks like a matter of providing the `--source` command line option, or alternatively `cd` into the app folder, because the CLI is not finding the `docker-compose.yml` file. Something like:
```
$ balena push 4OREgolf --source screenly-ose-master/screenly-ose-master
or
$ cd screenly-ose-master/screenly-ose-master
$ balena push 4OREgolf
```
Note: before you copy-and-paste the above, from the screenshot I wasn't sure if the spelling of `4O` was four-zero or four-oh.

As this looks like a troubleshooting issue rather than a CLI bug (though I agree that the error message could be more helpful...), for further guidance I would recommend that you created a post in the [balenaCloud forum](https://forums.balena.io/c/balena-cloud), where balena's support team or the community will be happy to help.

**Comment by pcasey92** [comment]
I see. I understand what you're saying. Thank you so much. Now I have to go on to another post for another error. haha
