### ISSUE TITLE
balena ssh not logging into application container by default

### ISSUE THREAD

**Issue by skotzko** [balena-io/balena-cli#1315]
- **balena CLI version:** 11.2.2
- **Operating system version:** macOS 10.14.5
- **32/64 bit OS and processor:** 64-bit
- **Install method:** balena-cli-v11.3.1-macOS-x64-installer-BETA.pkg

---

I just installed the CLI yesterday, but whenever I try to log into my devices it automatically drops me into the host container, even when I don't supply the `-s` flag. 

Example:

```
$ balena ssh <device uuid>
=============================================================
    Welcome to balenaOS
=============================================================
root@4de8df3:~#
```

is exactly the same as providing the `-s` flag:

```
$ balena ssh <device uuid> -s
=============================================================
    Welcome to balenaOS
=============================================================
root@4de8df3:~#
```

Both drop me into the host container, not my application container. 

After digging around, the only way I can get into my application container is to run `balena ssh <device uuid> main`

Isn't the default behavior of `balena ssh` supposed to be logging into the application container?

**Comment by pdcastro** [comment]
@skotzko, thank you for reporting this issue. It turns out that it is one of several major changes in the CLI v11: "major" both in terms of new features and in the [semantic versioning sense](https://semver.org/), i.e. a change from 10.x.x to 11.0.0 implies that some non-backwards-compatible changes were made. The [CHANGELOG](https://github.com/balena-io/balena-cli/blob/master/CHANGELOG.md#1100---2019-06-04) has a bullet point for it:

[11.0.0 - 2019-06-04](https://github.com/balena-io/balena-cli/blob/master/CHANGELOG.md#1100---2019-06-04)
* Update balena ssh command to support local devices and multicontainer

One of the major new features offered by `balena ssh` is support for multiservice / multicontainer apps (can you believe that until a few weeks ago they weren't supported?) :-)

Compare the `balena help ssh` output between v10.17.5 and v11.x.x:
```
# v10.17.5
$ balena help ssh
Usage: ssh [uuid]
...
Examples:
	$ balena ssh 7cf02a6 -s
```
```
# v11.3.1
$ balena help ssh
Usage: ssh <applicationOrDevice> [serviceName]
...
If a service name is not provided, a shell will be opened on the host OS.
...
Examples:
	balena ssh f49cefd my-service
```

If you're interested, here's also a link to the [pull request](https://github.com/balena-io/balena-cli/pull/1215/files).

**Comment by pdcastro** [comment]
Closing this issue given the advice above, but feel free to add comments or reopen it as needed.
