### ISSUE TITLE
cd ../ folder name doesn't work

### ISSUE THREAD

**Issue by quentinfabrie** [balena-io/balena-cli#1357]
- **balena CLI version:** e.g. 11.2.1 (output of the `"balena version"` command)
- **Operating system version:** e.g. Windows 10, Ubuntu 18.04, macOS 10.14.5
- **32/64 bit OS and processor:** e.g. 32-bit Windows on 64-bit Intel processor
- **Install method:** npm or zip or executable installer
- **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1

---

what is my problem
![image](https://user-images.githubusercontent.com/53113474/61578876-9d0f8a80-aafd-11e9-9d3a-649aecdb28a1.png)

**Comment by pdcastro** [comment]
@quentinfabrie, thanks for getting in touch. Before running `balena push`, you need to use the `cd` command to change the "working directory" (current folder) of the command prompt, so that the working directory is the same directory where the balenaSound zip file (downloaded from GitHub) was extracted to. The following links may be helpful:
* https://support.microsoft.com/en-us/help/14200/windows-compress-uncompress-zip-files
* https://www.digitalcitizen.life/command-prompt-how-use-basic-commands

As this sounds like a general support issue rather than a bug in the `balena-cli` tool, I suggest that you create a thread in the balenaCloud forum (link below), which is monitored by balena's support agents and the wider community:
https://forums.balena.io/c/balena-cloud
