### ISSUE TITLE
Run sanity project checks before push / deploy / build commands

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1421]
In the case of `balena push`, for example, the CLI will create a tar stream of current working dir -- which is _assumed_ to be a balena project -- and send the whole thing to the balenaCloud builder. If the user accidentally runs `balena push` on their homedir, it could mean gigabytes of uploaded data only for the cloud builder to respond that a Dockerfile was not found at the root of the project directory, or other unintuitive errors. A simple improvement would be for the CLI to check that the current working directory containers a `Dockerfile` or a `docker-compose.yml` file or `package.json` file, as the three currently accepted project types, before sending anything to the cloud builders.

In the case of `balena build` or `balena deploy --build`, the tar stream will be sent to a docker daemon (local or remote IP-address/port) instead of the cloud builder, so not as bad but it would also benefit from the preliminary sanity check.

**Comment by pdcastro** [comment]
Example why this is needed: issue #1103

**Comment by jimsynz** [comment]
Related to this issue is when you have a multi-container application and you accidentally run `balena push ...` inside one of the service subdirectories balena sees that you have a `Dockerfile.template` in this directory and happily redeploys your application as a single-container app.
Some suggestions:
1. check if there is a `docker-compose.yml` in a parent directory and query the user for confirmation.
2. check if the command is run from a subdirectory of the local git repo and either query for confirmation or just assume that they want to push from the root.
3. detect if a push would change the service topology of the application (ie would add or remove services) and ask the user for confirmation.

**Comment by pdcastro** [comment]
This issue (as originally described) was implemented in CLI release 11.27.0. @jimsynz, I've moved your comment / suggestions (thanks!) to a new issue, #1621. There is also complementary issue #1620.
