### ISSUE TITLE
Release builds for armv7hf and arm64

### ISSUE THREAD

**Issue by siredmar** [balena-io/balena-cli#1450]
It would be nice to have the balena-cli builds ready to use for armv7hf and arm64 in the releases download section.
Would that be much work to integrate those builds for arm in your CI chain?
That would eliminate the need for us (or many other?) to build balena cli from source for our target archs.

**Comment by pdcastro** [comment]
Thanks for the suggestion. I'd like to understand a bit more about the use case, i.e. the need for running balena-cli on an ARM architecture. Usually balena-cli is executed on development machines (laptop / desktop computers) or cloud CI environments (AWS, Travis...) which typically have x86 processors, rather than for example on balena devices which often have ARM processors. For x86 platforms, balena-cli offers pre-compiled standalone zip packages (and Mac / Windows native installers) that avoid the need to build balena-cli from source.

In relation to the `balena build` and `balena deploy --build` commands, when building images for the ARM architecture, the `--host` and `--port` options can be used to select a remote Docker or balenaEngine daemon which may be running on a balena device. For example, I would run the following on my x86 Mac laptop:
```
balena build project/folder -a test-rpi -h 192.168.1.10 -p 2375
```
So balena-cli runs on x86 and balenaEngine runs on ARM.

For other balena commands, it may or may not make sense to use the [balena API](https://www.balena.io/docs/reference/api/overview/) directly.

**Comment by pdcastro** [comment]
Connects to #845 (CLI does not install on arm64)

**Comment by pdcastro** [comment]
Note: There is a fresh need / use case for this issue's feature request in the "balena IDE" project where a development environment (IDE, including the CLI) is installed as a Docker container on the device itself.
