### ISSUE TITLE
`balena device` commands do not accept ID, just UUID

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1457]
- **balena CLI version:** 11.3.2

---

`balena devices` returns as the first column each device's ID, but subsequent `balena device` commands only accept UUID. Maybe I'm just be pedantic, but the ordering of the columns leads me to believe the ID is more important as a unique identifier than the UUID, and I would expect that the commands work with either UUID or ID.

**Comment by thgreasi** [comment]
@xginn8 I think that this is intentional, since there was an effort to move away from device IDs in favor of device UUIDs.
The thinking was that it would make things easier for the users when we implemented `balena leave/join` and user can move devices across instances.
Here are some related SDK & UI PRs:
See: https://github.com/balena-io/balena-sdk/pull/431
See: https://github.com/balena-io/resin-ui/pull/1346

cc: @pdcastro @shaunmulligan

**Comment by pdcastro** [comment]
Is it possible to reliably distinguish between an ID (typically numeric, looks like an integer with a variable number of digits) and a 7-char "short" UUID? For example, using a regular expression. I think the answer is no. In this case, what about introducing an _optional prefix_ like `id:1234567` or `uuid:1234567` to distinguish between the two?

**Comment by pdcastro** [comment]
Connects to #672 (Ensure all device functionality accepts UUIDs and short UUIDs)

**Comment by shaunmulligan** [comment]
@pdcastro what @xginn8 says is correct, we actively want to move away from device IDs. From what I recall the problem is that device IDs are not unique when we start having different backends like openBalena, balenaMachine, etc. We actually want to move to having uuids for apps as well as this will allow easier transfer between instances in the future.

**Comment by pdcastro** [comment]
> we actively want to move away from device IDs

OK - so the idea of allowing an `"id:"` prefix would count as "encouraging" the use of IDs, which is not wanted. In this case, perhaps the only actionable point in this Github issue is to change the ordering of the columns as pointed out by @xginn8, so that the UUID is listed first. Perhaps we should even drop the ID column in the output of the `balena device` command.

**Comment by shaunmulligan** [comment]
@pdcastro yeah we should try not surface IDs. Changing the ordering we should do for sure and perhaps remove the ID column completely (might be worth bringing to a production call?)

**Comment by srlowe** [comment]
@pdcastro Shaun's suggestion of removing the ID columns from the tables sounds like it would tie in well with the upcoming changes to the table output (and decisions about which columns to show by default) - we could remove ID from the default view.

**Comment by pdcastro** [comment]
@srlowe, agreed. There was the question of whether it would be a breaking change for v13, but either way it sounds like a good idea.
