### ISSUE TITLE
Login to Web Dashboard Does Not Work

### ISSUE THREAD

**Issue by JGHar** [balena-io/balena-cli#1458]
I am trying to get Balena Sound working.

I am unable to connect to the Web Dashboard via the Command Line. 

 I type in:
c:\balena-cli>balena login

This takes me to the option of:
How would you like to login?  web authorization <recommended>

Which I choose.  I am taken to loading page with the Balena Logo and a cog icon.  Then the page simply hangs and goes not further.

I have tried turning off my firewall and adblockers, but still no connection.

Can anyone help

**Comment by pdcastro** [comment]
I have not been able to reproduce the issue with CLI v11.12.0 or v11.13.1 on Windows 10. However, an alternative way of logging in is to copy-and-paste an authentication token (Session Token) from the dashboard to the CLI prompt. Check the attached screenshots for where to find and copy the authentication token, and where to paste it. On some Windows command prompts, note that sometimes the "paste" operation is done by clicking with the right mouse button on the terminal window, instead of typing CTRL-V.
![session_token](https://user-images.githubusercontent.com/15091591/66055605-b4bbb400-e52d-11e9-8717-0effb86e8577.png)
![session_token2](https://user-images.githubusercontent.com/15091591/66055046-d9fbf280-e52c-11e9-9e4f-601ab3e5ab5a.png)

**Comment by pdcastro** [comment]
@JGHar, were you able to solve this issue? If web authorization still doesn't work for you, could you share the CLI version (output of `balena version`), Windows version and web browser version? So that I could try to reproduce it, and then fix it. Thank you for reporting it.
