### ISSUE TITLE
'SELF_SIGNED_CERT_IN_CHAIN' error on balena login

### ISSUE THREAD

**Issue by GVersluiss** [balena-io/balena-cli#1487]
- **balena CLI version:** 11.17.0
- **Operating system version:** Windows 10
- **OS and processor:** Windows 64-bit Intel processor
- **Install method:** executable installer
---

When executing command 'balena login' (and entering credentials) I get the error

`SELF_SIGNED_CERT_IN_CHAIN: request to <mydomain>/login_ failed, reason: self signed certificate in certificate chain`

I followed the getting-started-docs closely although I think the  'Install self-signed certificates'-part is confusing. Especially what should be ran on your local machine and what on your open-balena-machine.

What I did on my open-balena machine:

1. Ran the following commands:
- `export NODE_EXTRA_CA_CERTS=~/open-balena/config/certs/root/ca.crt`
- `sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt`
- `sudo update-ca-certificates`
- `cat $NODE_EXTRA_CA_CERTS` shows my certificate 

2. Also restarted docker with `sudo systemctl restart docker`

What I did on my local machine:

1. Installed balena-cli using the executable-installer
2. Manually added **_balenarc.yml** to '/Users/<user>' directory as it was not added by the installer
3. Set the correct `balenaUrl` inside the **_balenarc.yml**
4. Downloaded the **ca.crt** from my open-balena machine
5. Installed the **ca.crt** on my windows machine using `certutil -addstore -f "ROOT" ca.crt`
6. Ran `balena login`

Anything obvious I'm missing?

**Comment by pdcastro** [comment]
@GVersluiss, I have not tried the procedure myself, but reading the [openBalena Getting Started](https://www.balena.io/open/docs/getting-started/), I gather that the `export NODE_EXTRA_CA_CERTS=<path-to-ca.crt>` command should be executed on the machine / shell where you are running `balena-cli`, which I think you referred to as "local machine", rather than on the open-balena machine. For extra context, the NODE_EXTRA_CA_CERTS environment variable will tell [Node.js](https://nodejs.org), which is the Javascript interpreter that powers the balena CLI, where to find the `ca.crt` file.

Note also however that the `export NODE_EXTRA_CA_CERTS="path-to-ca.crt"` syntax is only valid for Unix shells like `sh` or `bash`, not on a Windows `cmd.exe` Command Prompt or the [PowerShell](https://docs.microsoft.com/en-gb/powershell/scripting/getting-started/starting-windows-powershell?view=powershell-6):

Windows command prompt: (cmd.exe)
```text
C:\Users\paulo>set NODE_EXTRA_CA_CERTS=C:\path with spaces\ca.crt
C:\Users\paulo>echo %NODE_EXTRA_CA_CERTS%
C:\path with spaces\ca.crt
```
Windows PowerShell:
```
PS C:\Users\paulo> $Env:NODE_EXTRA_CA_CERTS="C:\path with spaces\ca.crt"
PS C:\Users\paulo> echo $Env:NODE_EXTRA_CA_CERTS
C:\path with spaces\ca.crt
```

Or you can also set an environment variable globally via the Windows Control Panel, as explained in [this page](https://www.computerhope.com/issues/ch000549.htm).

You also have the option of using Unix shell on Windows. Check the documentation section "Choosing a shell" in the following page for some options: https://www.balena.io/docs/reference/cli/#choosing-a-shell-command-promptterminal

**Comment by GVersluiss** [comment]
I think you are correct and that's where I got on the wrong trail. I didn't see equivalent commands for windows regarding the `export NODE_EXTRA_CA_CERTS=~/open-balena/config/certs/root/ca.crt`.  It also has the same path as the open-balena machine so I assumed I had to execute it on the open-balena machine.

Thanks for pointing me in the right direction. I will try it later this evening and give an update.

**Comment by GVersluiss** [comment]
What you said worked. After executing the powershell commands you provided it worked. However I got an 'Unauthorized' error right after that. I didn't trust it so just to be sure I did all the steps all over again and also used a different domain this time. Funny thing is; I did all my previous steps as before (only a different domain this time) and I am stuck again on the 'SELF_SIGNED_CERT_IN_CHAIN' error again.

But like you said; this doesn't appear to be a bug so I will continue this on de openBalena forum.
