### ISSUE TITLE
Debug mode still active with env var `DEBUG=0` 

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1502]
`DEBUG=1` for debugging implies that it can be disabled with `DEBUG=0`.  However debugging is still active, and you need to `unset DEBUG` to deactivate.

- **balena CLI version:** e.g. 11.17.3
- **Operating system version:** Ubuntu 19.10
- **32/64 bit OS and processor:** 64
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v12.13.0, npm v6.12.0

**Comment by pdcastro** [comment]
Perhaps the values 0, "no" and "false" (case insensitive) could be treated as disabling debug (in addition to unsetting the variable), and any other non-empty value treated as enabling debug. (If an env var can hold the empty string (can it?), it should probably be considered as disabling debug as well.)

**Comment by srlowe** [comment]
Linux env vars can be empty, but not windows.

**Comment by codewithcheese** [comment]
Hi @srlowe @pdcastro. I'm interested to resolve this issue as my first contribution to `balena-cli`.

What do you think about this approach?

Running a `find` shows that `DEBUG` truthy evaluation is done in a bunch of files. I would create a new function called `isDebugEnabled` in `lib/utils/helpers.ts` that would return `false` for `undefined` `"0"`, `"no"`, `"false"`, or `""` and `true` for all other values.

I would then replace all usages of `DEBUG` truthy evaluation with the function call.

Since the changes touches many file, I'm concerned how I would test. Any tips?

![Selection_004](https://user-images.githubusercontent.com/989237/73549693-6a6c2480-4486-11ea-8e15-3bffa77a6cba.png)

**Comment by codewithcheese** [comment]
Now, thinking supporting other "falsey" values only serves to add confusion. For example do we also support capitalization? `export DEBUG=NO` `export DEBUG=YES`?

It seems reasonable that someone would want to switch from DEBUG=1 to DEBUG=0. I doubt it's reasonable to support people who wish to freestyle with truthiness :)
