### ISSUE TITLE
When configuring the OS with a config file generated with 'network ethernet', balena-cli asks the type of network

### ISSUE THREAD

**Issue by ffissore** [balena-io/balena-cli#1515]
I'm following the [advanced masterclass](https://github.com/balena-io-projects/balena-cli-advanced-masterclass).
When I generate a config file with wifi credentials and configure the os, everything runs fine

```bash
$ balena config generate --version v2.43.0+rev1 --application cliApp --appUpdatePollInterval 10 --network wifi --wifiSsid MyNetworkSSID --wifiKey myw1f1n3tw0rk -o wifi-config.json
$ balena os configure rpi3.img --app cliApp --config wifi-config.json 
Configuring operating system image
```

However, when I generate a file specifying `--network ethernet` and use that to configure the os, I'm interactively asked the type of network
```bash
$ balena config generate --version v2.43.0+rev1 --application cliApp --appUpdatePollInterval 10 --network ethernet -o homepi.json
$ balena os configure rpi3.img --app cliApp --config homepi.json 
? Network Connection (Use arrow keys)
❯ ethernet 
  wifi 
```

I expected the same behaviour (no interactivity) in both cases.

Comparing the two generated json files, the one without wifi information has nothing that says that the chosen network was of type ethernet: this might be why `os configure` asks it again

- **balena CLI version:** 11.18.2
- **Operating system version:** Ubuntu
- **32/64 bit OS and processor:** 64bit
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v10.16.3 and npm 6.9.0

**Comment by pdcastro** [comment]
@ffissore, thanks for reporting this issue. Some initial comments/thoughts. The `os configure` command needs to find "answers" to its configuration questions. It looks for the answers in the given command-line options (flags, switches), in the given `config.json` file, and then asks interactively:

```
$ balena help os configure
...
  Configuration settings such as WiFi authentication will be taken from the
  following sources, in precedence order:
  1. Command-line options like `--config-wifi-ssid`
  2. A given `config.json` file specified with the `--config` option.
  3. User input through interactive prompts (text menus).
```
There is a `--config-network=ethernet` flag that avoids the interactive prompt regarding the network type (ethernet _vs._ WiFi):
```
$ balena help os configure
...
  --config-network=ethernet|wifi    device network type (non-interactive configuration)
```
When this flag is not provided, I understand the inconsistency of an interactive prompt being raised in the case of Ethernet and not WiFi, in the latter case provided that the `config.json` file contains WiFi settings. A complication / explanation is that, with balenaOS 2.x (unlike 1.x), the `config.json` file is not required to have WiFi settings, whether or not the OS image should be configured with WiFi. (In balenaOS 2.x, WiFi is configured via NetworkManager connections profiles in the `system-connections` folder, instead of `config.json`.)

Therefore, we cannot assume Ethernet simply because the `config.json` file does not contain WiFi settings. A consistency change that could be done is to always ask for the network type, even when the `config.json` file contains WiFi settings. But this feels a bit "pedantic", considering that the CLI currently can only configure images with a single NetworkManager connection profile.

A related issue is #1498 [Allow custom network connections to be generated](https://github.com/balena-io/balena-cli/issues/1498). Also, a project named "CLI Configuration" is starting to revisit and update the OS configuration "story," with freedom to make breaking changes in CLI commands (for a future semver-major CLI release), so hopefully the consistency across commands will be improved then. CC: @hedss
