### ISSUE TITLE
Error pushing image using hostname

### ISSUE THREAD

**Issue by ll01** [balena-io/balena-cli#1528]
- **balena CLI version:11.18.3
- **Operating system version: Windows 10
- **32/64 bit OS and processor:64-bit Windows on 64-bit AMD processor
- **Install method: executable installer

---

my pi's hostname is pi4-proxy

If I run the command Balena push pi4-proxy.local I get an error.
However, if I enter the IP address as the command it works fine.
The error It outputs is:

ENOTFOUND: getaddrinfo ENOTFOUND pi4-proxy.local pi4-proxy.local:48484
Error: getaddrinfo ENOTFOUND pi4-proxy.local pi4-proxy.local:48484
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
From previous event:
    at Function.promisifiedRequest (C:\Program Files\balena-cli\client\build\utils\device\api.js:128:25)
    at DeviceAPI.getDeviceInformation (C:\Program Files\balena-cli\client\build\utils\device\api.js:42:26)
    at Object.deployToDevice (C:\Program Files\balena-cli\client\build\utils\device\deploy.js:91:34)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

![image](https://user-images.githubusercontent.com/6953881/70274008-3d133b00-17a3-11ea-88c1-53c5e27a1eb2.png)

**Comment by pdcastro** [comment]
@ll01, thank you for reporting this issue. How are your RPi and your laptop/desktop computer connected to the local network? For example:
* Connected to each other by a direct Ethernet cable, with the laptop providing internet access through "internet connection sharing". 
* Or both connected to a WiFi router -- is it the same WiFi router for both?
* Or some other arrangement?

Also, is the `balena scan` command able to list the device?

I wonder if this could be the same issue as #1518 (Livepush using `.local` address fails on Windows (with incorrect error)). @srlowe, do you think this is something that could be fixed by PR #1525 (Introduce workaround for windows dns issue on local `balena push`)?

**Comment by srlowe** [comment]
@pdcastro Yes, this looks very much like the same issue, which #1525 should fix!

**Comment by srlowe** [comment]
@ll01 Please could you try with latest, v11.19.1, and see if that fixes your issue?  
cc @pdcastro

**Comment by pdcastro** [comment]
Closing this issue with the understanding that it was fixed in CLI release 11.19.1. If you're still experiencing the issue, just leave a comment and we will reopen the issue it and investigate it further.

**Comment by evanlesmez** [comment]
I just ran into a similar problem:

 ```bash
ENOTFOUND: getaddrinfo ENOTFOUND 59bda95.local

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

I can ssh to the device fine: 

```bash
[ev@archy Babylon-Farm]$ balena ssh 59bda95
=============================================================
    Welcome to balenaOS
=============================================================

```

I am running arch linux with balena-cli version 12.26.1

**Comment by pdcastro** [comment]
@evanlesmez, does `balena scan` report the device? Is Avahi installed and running as a service? See note re `balena scan` requirements on this page: https://github.com/balena-io/balena-cli/blob/master/INSTALL-LINUX.md#balena-scan

This GitHub issue was specific to Windows name resolution, so I don't think it will be the same thing. But we can of course open a new issue. Typically this error is because of missing Avahi, or a local network firewall or router block mDNS packets. Something else that blocks mDNS is "internet connection sharing" -- for example, if internet access to the device is provided by a laptop / desktop computer, rather than a router.
