### ISSUE TITLE
Unable to install [Archlinux][NPM]

### ISSUE THREAD

**Issue by Merith-TK** [balena-io/balena-cli#1536]
- **Operating system version:** Archlinux
- **32/64 bit OS and processor:** 64bit AMD
- **Install method:** npm/AUR
- **If npm install, Node.js and npm version:** 6.12.1

---

[2019-12-17T02_29_28_011Z-debug.log](https://github.com/balena-io/balena-cli/files/3971190/2019-12-17T02_29_28_011Z-debug.log)

I am totally unable to install this at all

**Comment by sthysel** [comment]
I used the zip here https://github.com/balena-io/balena-cli/releases and unzipped it like it was 1984...
did work though. balena-cli does not run on the latest node-js. The npn install also fails and I have little interest myself in bootstrapping a silly nodejs dev env.

Anyway, the zip worked for me on Arch.

**Comment by tafli** [comment]
I got the same problem and found the reason for it: ext2fs node module.
There is currently a problem with node v13. Should be fixed with soon (https://github.com/balena-io/node-ext2fs/pull/70) but until then switch to node v12 for installation (`nvm install 12` and `nvm use 12`).

**Comment by sthysel** [comment]
The balena-cli AUR package got updated today, https://aur.archlinux.org/packages/balena-cli/ so assuming you have not other system dependencies on node-js a $ yay -S balena-cli, or similar should work. It basically just drops the system nodejs to 12.

**Comment by xginn8** [comment]
This dependency has now been added to the package. I am the maintainer of that package, though it is "unofficial" and I keep it up to date in my spare time as a best effort. I've made sure I'm monitoring the comments there, so please post any comments or issues directly on the package itself!

**Comment by pdcastro** [comment]
> though it is "unofficial" and I keep it up to date in my spare time as a best effort

Thank you @xginn8 for fixing it, and everyone else for reporting it! In case anyone wonders what the "official" package is, well for Linux we currently have the 1984 zip package* :-) that @sthysel mentioned, or the `npm` command line -- both documented in the [INSTALL file](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md).

\* (Hey, a zip file may taste like 1984 but it's automatically generated and immediately available on every CLI minor release, and the install option least likely to face system compatibility or dependency issues, as all dependencies are built in!) :-)

The "official" plan we currently have for Linux packages is to create "Debian packages" that could be installed on Ubuntu or Debian systems with the `apt install` command (issue #1520). My thinking / hope is to package the binary (contents of the zip file) rather than compiling the CLI modules when `apt install` is executed, as this would avoid any dependencies on the system's Node.js installation and any other build-time dependencies.

**Comment by sthysel** [comment]
> This dependency has now been added to the package. I am the maintainer of that package, though it is "unofficial" and I keep it up to date in my spare time as a best effort. I've made sure I'm monitoring the comments there, so please post any comments or issues directly on the package itself!

Thanks mate, much appreciated.
