### ISSUE TITLE
`balena ssh <ip-address>` does not support IPv6 addresses.

### ISSUE THREAD

**Issue by jimsynz** [balena-io/balena-cli#1540]
- **balena CLI version:** 11.18.0
- **Operating system version:** macOS 10.15.2
- **32/64 bit OS and processor:** 64-bit Intel
- **Install method:** homebrew installer
- **If npm install, Node.js and npm version:** Node v12.9.1 and NPM v6.10.2.

---

Hi team.

I noticed when talking to a customer today that doing `balena ssh <ip-address>` only works for IPv4 addresses and not IPv6 addresses.  I noticed this due to the fact that the user's device had no IPv4 address on the local interface (both ends were expecting the other to supply DHCP details) however the device had an IPv6 link local address as expected.  It should have been possible to ssh to the device using that link local address, however this is not supported.

As an example, I have devices at home which is a dual-stacked IPv4 and IPv6 network:

```
$ ns-sd -G v4v6 552d8d9.local
DATE: ---Wed 18 Dec 2019---
 8:05:33.650  ...STARTING...
Timestamp     A/R    Flags if Hostname                               Address                                      TTL
 8:05:33.831  Add        3  6 552d8d9.local.                         2002:7A3A:5C54:0000:791A:73A2:9D78:4A7C%<0>  120
 8:05:33.831  Add        2  6 552d8d9.local.                         FD22:35FF:F4DE:0010:B6B0:BB4C:52BC:DD4B%<0>  120
 8:05:33.956  Add        2  6 552d8d9.local.                         192.168.165.221                              120
^C
$ balena ssh FD22:35FF:F4DE:0010:B6B0:BB4C:52BC:DD4B
Device or application not found: FD22:35FF:F4DE:0010:B6B0:BB4C:52BC:DD4B
$ balena ssh 2002:7A3A:5C54:0000:791A:73A2:9D78:4A7C
Device or application not found: 2002:7A3A:5C54:0000:791A:73A2:9D78:4A7C
$ nc -z FD22:35FF:F4DE:0010:B6B0:BB4C:52BC:DD4B 22222
Connection to FD22:35FF:F4DE:0010:B6B0:BB4C:52BC:DD4B port 22222 [tcp/*] succeeded!
$ nc -z 2002:7A3A:5C54:0000:791A:73A2:9D78:4A7C 22222
Connection to 2002:7A3A:5C54:0000:791A:73A2:9D78:4A7C port 22222 [tcp/*] succeeded!
```

Cheers!

**Comment by pdcastro** [comment]
When implementing this, we should consider requiring square brackets around the IPv6 address [like web browsers do in the URL field](https://superuser.com/questions/367780/how-to-connect-a-website-has-only-ipv6-address-without-domain-name), because the combination of hexadecimal characters and abbreviated IPv6 syntax like `::1` makes it harder to distinguish with certainty between a device UUID, an application name and an arbitrary IPv6 address.

By the way, while we have a convenience "looks like" detection to distinguish between app name, device UUID and IP address, I always thought we could also have flags that 'force' treatment of the parameter as a specific type, to cover corner cases.

**Comment by jimsynz** [comment]
> By the way, while we have a convenience "looks like" detection to distinguish between app name, device UUID and IP address, I always thought we could also have flags that 'force' treatment of the parameter as a specific type, to cover corner cases.

Now that's a damn fine idea.
