### ISSUE TITLE
I get Invalid MBR boot signature when configuring a device, FAQ asked me to delete a non existent cache

### ISSUE THREAD

**Issue by Bazmundi** [balena-io/balena-cli#1541]
- **balena CLI version:** e.g. 11.20.2
- **Operating system version:** e.g. Windows 10b
- **64 bit OS and processor:**  64-bit Intel processor
- **Install method:** executable installer

- Fresh first time install.
- Following https://www.balena.io/os/docs/orange-pi-zero/getting-started/
- Grabbed opizero image from link provided.
- Downloaded and installed cli.
- Got to configuration step and got the MBR message.
- I went to FAQ to find hint that I should delete cache, since (apparently) the img may have been corrupted on download, but alas no cache was there to delete.  The _balena directory was there but it was empty.

So, if I am getting the MBR error and there is no cache then FAQ falls short of explaining what to do.  Any ideas please.  It otherwise appears to be a bug since this is fresh install and run against empty cache.

**Comment by pdcastro** [comment]
@Bazmundi, thanks for trying balenaOS / balena CLI and reporting this issue. So far I have not been able to reproduce the error:
```
C:\Users\paulo\Downloads>balena version -a
balena-cli version "11.20.2"
Node.js version "8.15.1"

C:\Users\paulo\Downloads>balena local configure balena.img
? Network SSID myssid
? Network Key mypass
? Do you want to set advanced settings? No
Done!

C:\Users\paulo\Downloads>balena local configure balena.img
? Network SSID myssid
? Network Key mypass
? Do you want to set advanced settings? Yes
? Device Hostname myhost
? Do you want to enable persistent logging? Yes
Done!
```
I was testing on Windows 10 Home version 1903, CLI version 11.20.2 (executable installer) on an Administrative Command Prompt.
I have a few questions / suggestions:

* Were you also using an Administrative Command Prompt? (As opposed to the Windows Subsystem for Linux, PowerShell, MinGW, MSYS, Cygwin, etc.)
* Perhaps it was the `balena.zip` or `balena.img` file itself that got corrupted, instead of the CLI cache. Try deleting them and re-downloading the zip file. On a [PowerShell](https://docs.microsoft.com/en-gb/powershell/scripting/install/installing-windows-powershell?view=powershell-6) prompt, here I get the following hash value - check that yours match:
```
PS C:\Users\paulo\Downloads> Get-FileHash balena.img.zip
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          B7C32B4253E00AEBB823FD6510335784BC7313AC60DFD42FC9B15CA5C7B13BC1       C:\Users\paulo\Downloads\bale...
```

* Try setting the DEBUG=1 environment variable and running `local configure` again, so perhaps it gives us some additional clue:
```
C:\Users\paulo\Downloads>set DEBUG=1

C:\Users\paulo\Downloads>balena local configure balena.img
[debug] original argv0="C:\Program Files\balena-cli\bin\\..\client\bin\node.exe" argv=[C:\Program Files\balena-cli\client\bin\node.exe,C:\Program Files\balena-cli\client\bin\run,local,configure,balena.img] length=5
? Network SSID myssid
? Network Key mypass
? Do you want to set advanced settings? No
Done!
```

**Comment by pdcastro** [comment]
Closing this issue for lack of response / activity. Feel free to reply / add comments even if it is closed, as I can then reopen it.

**Comment by dvanduzer** [comment]
I also ran into this message, and found it was because I was trying to configure the compressed img.zip instead of the unzipped balena.img file. After unzipping the download, everything worked.
