### ISSUE TITLE
[Jetson Nano] `local configure`: Error: Unsupported filesystem

### ISSUE THREAD

**Issue by lackdaz** [balena-io/balena-cli#1632]
- **balena CLI version:** e.g. 11.28.4
- **Operating system version:** MacOSX 10.14.6
- **32/64 bit OS and processor:** 64-bit, 3.1 Ghz Intel Core i5
- **Install method:** MacOSX executable installer
---
I'm trying out balena for the jetson nano and just following your steps on "Getting Started" but I can't seem to hit a roadblock when configuring the base image:

Unsupported filesystem when `sudo balena local configure ~/Downloads/balena.img`

Expected: 
```
$ sudo balena local configure ~/Downloads/balena.img
? Network SSID I_Love_Unicorns
? Network Key superSecretPassword
? Do you want to set advanced settings? Yes
? Device Hostname mydevice
? Do you want to enable persistent logging? no
Done!
```
Outcome:
```
Unsupported filesystem.

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, "$env:DEBUG = 1" on
powershell, or "export DEBUG=1" on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

Setting DEBUG=1 via `export DEBUG=1` did not reveal any more verbose error logs.

Can someone point out what is going wrong?

**Comment by afitzek** [comment]
It seems like this is not supported for the jetson nano yet, because it has a specific partition layout. See: https://www.flowdock.com/app/rulemotion/r-resinos/threads/rwZud2b2lh8AteFX2Ii8oQL7rI7

**Comment by zvin** [comment]
@pdcastro the fix would be to use the [device type boot partition number](https://github.com/balena-os/balena-jetson/blob/master/jetson-nano.coffee#L40) instead of [the hardcoded one](https://github.com/balena-io/balena-cli/blob/5cf407b48351fecfd81e7d7e32cd6fe01f6a344a/lib/actions-oclif/os/configure.ts#L29)

**Comment by pdcastro** [comment]
> (at)pdcastro the fix would be to use the [device type boot partition number](https://github.com/balena-os/balena-jetson/blob/master/jetson-nano.coffee#L40) instead of [the hardcoded one](https://github.com/balena-io/balena-cli/blob/5cf407b48351fecfd81e7d7e32cd6fe01f6a344a/lib/actions-oclif/os/configure.ts#L29)

Thanks @zvin! 👍 By the way, I am not planning to work on this issue ahead of many others in the [ordered backlog](https://github.com/balena-io/balena-cli/milestone/2), so feel free to work on it if you would like to. :-)

**Comment by EdjeElectronics** [comment]
I assume you guys never got this fixed, because I still get the `Unsupported filesystem` error when I try configuring the Jetson Nano image from the [balenaOS downloads](https://www.balena.io/os/#download) page. Just trying to do what the instructions at https://www.balena.io/os/docs/jetson-nano/getting-started/ say, but it isn't working.

```
evan@Vortex:~$ sudo balena local configure balena-cloud-jetson-nano-2.67.3+rev2-dev-v12.3.0.img
[sudo] password for evan: 
Unsupported filesystem.

Additional information may be available with the `--debug` flag.

For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting
```

**Comment by pdcastro** [comment]
> the fix would be to use the [device type boot partition number](https://github.com/balena-os/balena-jetson/blob/master/jetson-nano.coffee#L40) instead of [the hardcoded one](https://github.com/balena-io/balena-cli/blob/5cf407b48351fecfd81e7d7e32cd6fe01f6a344a/lib/actions-oclif/os/configure.ts#L29)

@zvin, do you know how the CLI could get hold of that partition number? Is it available via some API or SDK call? I guess we could further hardcode other numbers along the lines of:
```
const BOOT_PARTITION = deviceTypeName.includes(`jetson-nano`) ? 12 : 1;
```
But ideally the CLI would query something closer to the source of truth. At least, it might be hardcode in some upstream module like `balena-io-modules/resin-device-operations` or `balena-io-modules/balena-image-fs`. What do you think?

By the way, I also see that [resin-image-fs](https://www.npmjs.com/package/resin-image-fs) is deprecated in favor of [balena-image-fs](https://www.npmjs.com/package/balena-image-fs). The CLI currently uses both (in different areas of the codebase). I believe @mbalamat has been working on replacing `resin-image-fs` with `balena-image-fs` in the context of adding support for Node.js v14. Is the update to `balena-image-fs` also a requirement to solve this issue?

**Comment by zvin** [comment]
@pdcastro you could get the device-type from the api but it might be wrong about the partition number depending on the image version.

A more robust solution would be to look for something that looks like a boot partition using balena-image-fs and partitioninfo (which is already a dependency of balena-image-fs):
```js
async function getBootPartition(imagePath) {
    return await filedisk.withOpenFile(imagePath, 'r', async (handle) => {
        const disk = new filedisk.FileDisk(handle, true, false, false);
        const { partitions } = await partitioninfo.getPartitions(disk, { includeExtended: false, inclideLogical: true });
        for (const { index } of partitions) {
            try {
                await interact(disk, index, async (fs) => {
                    const statAsync = promisify(fs.stat);
                    const stats = await statAsync('/device-type.json')
                    if (stats.isFile()) {
                        return index;
                    }
                });
            } catch (error) {
                // noop
            }
        }
    }
}
```

 * https://github.com/balena-io-modules/balena-image-fs/
 * https://github.com/balena-io-modules/file-disk
 * https://github.com/balena-io-modules/partitioninfo#module_partitioninfo..getPartitions

**Comment by cyclair-tech** [comment]
Hi,

I have the same error while trying to configure a custom balena image.

How can I configure my custom image to connect to my dashboard ? I'm trying to configure a ***rootfs** img.
Thanks

**Comment by quentingllmt** [comment]
Hi,

I'm trying to configure a custom balena os image but I'm facing the same issue. 

How can I configure my custom image to connect to my dashboard ? I'm trying to configure the ***rootfs*** output image after the yocto build.

Thanks

**Comment by pdcastro** [comment]
@quentingllmt, I suggest you reach out to balena's support team. If you have paid plan, you can use the private support service. Otherwise, you can search or create a new thread in https://forums.balena.io/c/product-support/42
(private support gives you higher priority).

For some general pointers, the partition layout of balenaOS is explained here:
https://www.balena.io/docs/reference/OS/overview/2.x/#image-partition-layout

The boot partition contains the `config.json` file, which is the main configuration file:
https://www.balena.io/docs/reference/OS/configuration/

For networking configuration (so that the device can connect to the internet and the balenaCloud web dashboard), NetworkManager connection profiles should be added to the `system-connections` folder of the boot partition, as further explained at:
https://www.balena.io/docs/reference/OS/network/2.x/

The balena CLI's `local configure` command would be conveniently creating or editing those files (`config.json` and `system-connections/resin-wifi`) in the boot partition, but the CLI does not yet understand the partition layout of some device types. I assume there would be a way for you to manually mount the image, identify the boot partition and copy or edit those files without the CLI.

**Comment by quentingllmt** [comment]
@pdcastro Thanks for that documentation and the tips about editing the `config.json` and `system-connections/resisin-wifi`. It works like a charm !

For all: You can download a custom `config.json` easily when adding a new device on the balena dashboard.

Hope to see the CLI supporting that soon !

Thanks !

**Comment by pdcastro** [comment]
Here are some steps to "manually" copy a `config.json` file and a NetworkManager connection profile named `balena-wifi` to an image file of a Jetson device (for which the balena CLI currently errors with "Unsupported filesystem"), using a colleague's [mount-image](https://gist.github.com/zvin/2717a09886b5aea19ce872257352e5de) Python script and a Ubuntu virtual machine conveniently instantiated with [multipass](https://multipass.run/).

If you are already using a Linux physical or virtual machine for other purposes, you can use it instead of `multipass`. I like `multipass` because it makes it quick and reproducible to create and destroy Ubuntu VMs, and easy to document the steps.

## Gather the files

In this example, I had the following files in the Downloads folder of the host OS (a Mac laptop):

* The image file, unzipped:  
`balena-cloud-jetson-xavier-nx-devkit-jetson-xavier-nx-devkit-2.67.3+rev5-v12.3.0.img`  
* `config.json`
* `balena-wifi` (the NetworkManager connection profile)
* `mount-image` script downloaded from:  
https://gist.githubusercontent.com/zvin/2717a09886b5aea19ce872257352e5de/raw/3ba74d1343f19841a1e37430cc2f94dbab26fa2e/mount-image

## Launch a Ubuntu 20.04 VM with `multipass`

Install Multipass as per instructions on https://multipass.run/
Then:

```
$ multipass launch -n vm1 -m 4G -d 50G -c 4 20.04
$ multipass list
Name                    State             IPv4             Image
vm1                     Running           192.168.1.4      Ubuntu 20.04 LTS
```

## Copy the files to the VM's `/tmp` folder

```
$ cd Downloads
$ multipass transfer mount-image config.json balena-wifi balena-cloud-jetson-xavier-nx-devkit-jetson-xavier-nx-devkit-2.67.3+rev5-v12.3.0.img vm1:/tmp
```

`multipass transfer` is a convenient way to copy the files, but you can also use `scp` or a "file sharing" folder or any other method. **However, do not execute the `mount-image` script directly over a file sharing folder.** The image file needs to be in the VM's local filesystem. Copy the files in, modify them, then copy them out.

## Install dependencies in the VM

```
$ multipass exec vm1 bash

# The following runs in the VM
$ sudo apt-get update && sudo apt-get -y install python3 python3-pip
$ sudo pip3 install sh
```

## Run `mount-image`

The `mount-image` script will open another command prompt that allows you list the contents of the image and copy files in and out.

```
$ multipass exec vm1 bash

# The following runs in the VM
$ cd /tmp
$ ls
balena-cloud-jetson-xavier-nx-devkit-jetson-xavier-nx-devkit-2.67.3+rev5-v12.3.0.img
balena-wifi
config.json
mount-image
...

$ chmod +x mount-image
$ sudo ./mount-image balena-cloud-jetson-xavier-nx-devkit-jetson-xavier-nx-devkit-2.67.3+rev5-v12.3.0.img
Warning: couldn't mount 1
Warning: couldn't mount 2
Warning: couldn't mount 3
Warning: couldn't mount 4
Warning: couldn't mount 5
Warning: couldn't mount 6
Warning: couldn't mount 7
Warning: couldn't mount 8
All image partitons mounted in /tmp/tmpymbp525t exit this shell to umount.

root@vm1:/tmp/tmpymbp525t# ls -l
total 61
drwxr-xr-x  2 root root  4096 May 14 20:58 1
drwxr-xr-x 13 root root  4096 Feb  4 17:12 10_resin-rootA
drwxr-xr-x  3 root root  4096 Feb  4 17:12 11_resin-rootB
drwxr-xr-x  3 root root  1024 Feb  4 17:12 12_resin-state
drwxr-xr-x  5 root root  4096 Jan 13 12:35 13_resin-data
drwxr-xr-x  2 root root  4096 May 14 20:58 2
drwxr-xr-x  2 root root  4096 May 14 20:58 3
drwxr-xr-x  2 root root  4096 May 14 20:58 4
drwxr-xr-x  2 root root  4096 May 14 20:58 5
drwxr-xr-x  2 root root  4096 May 14 20:58 6
drwxr-xr-x  2 root root  4096 May 14 20:58 7
drwxr-xr-x  2 root root  4096 May 14 20:58 8
drwxr-xr-x  5 root root 16384 Jan  1  1970 9_resin-boot

root@vm1:/tmp/tmpymbp525t# cp /tmp/config.json 9_resin-boot/
root@vm1:/tmp/tmpymbp525t# cp /tmp/balena-wifi 9_resin-boot/system-connections/

root@vm1:/tmp/tmpymbp525t# exit

$ exit
```

## Copy the modified image file back to the host OS

```
$ cd Downloads
$ multipass transfer vm1:/tmp/balena-cloud-jetson-xavier-nx-devkit-jetson-xavier-nx-devkit-2.67.3+rev5-v12.3.0.img .
```

Now the image file can be flashed.

## Cleanup

```
$ multipass stop vm1
$ multipass delete vm1
$ multipass purge
```

**Comment by pdcastro** [comment]
This issue should be resolved in CLI release 12.44.15 or later, 🎉  thanks to @zvin who provided the [core of the solution](https://github.com/balena-io/balena-cli/issues/1632#issuecomment-775998774), and thanks to @Kajatin who created PR #2267 to implement, test and deploy it, fixing both the `local configure` and the `os configure` commands. 🙏 💯

**Comment by shawaj** [comment]
@pdcastro I am getting this `unsupported filesystem` issue on a RockPi ESR image whilst doing `os configure`

Any thoughts as to why?

**Comment by Kajatin** [comment]
Hey @shawaj !

As I can see from [the RockPi coffee file](https://github.com/balena-os/balena-rockpi/blob/master/rockpi-4b-rk3399.coffee), the boot partition number is set to `partition: 4`. However, the [helper function](https://github.com/balena-io-modules/balena-config-json/blob/master/lib/utils.ts) that determines the correct boot partition number must return `undefined` instead.

You could try hard-code the partition number here: https://github.com/balena-io/balena-cli/blob/2b5c387313a9fb1bdf237cf8a0e6aeb33cd163b8/lib/commands/os/configure.ts#L318
Rebuild the CLI and see if that helps.

**Comment by pdcastro** [comment]
@shawaj, @Kajatin, try with a newer (latest) version of the balena CLI. CLI versions 12.53.0 and 12.54.5 changed the way how image partitions are identified, replacing hardcoding with runtime scanning to look for partition names (like `resin-boot`) (and, failing that, by attempting to read the contents of all partitions to find a `device-type.json` file).

And you mentioned an ESR image: CLI version 12.52.0 added support for downloading ESR images with the `os download` command, and the feature was improved in CLI versions 12.55.3 and 12.55.4.

With CLI version 12.55.4 (current latest), I was able to download and configure a balenaOS ESR image for the ROCK Pi 4B, as follows.

```sh
$ balena version
12.55.4

$ balena os download rockpi-4b-rk3399 --version v2021.10.5.prod -o rockpi-4b-rk3399-v2021.10.5.prod.img
Getting device operating system for rockpi-4b-rk3399
Downloading balenaOS version 2021.10.5.prod [========================] 100% eta 0s
balenaOS image version 2021.10.5.prod downloaded successfully

$ balena os configure rockpi-4b-rk3399-v2021.10.5.prod.img --version 2021.10.5 -f g_paulo_castro1/rock-pi-4b
? Network Connection wifi
? Wifi SSID foo
? Wifi Passphrase [hidden]
Configuring operating system image

# To confirm that `config.json` was updated by the `os configure` command:
$ sudo balena config read --json -d rockpi-4b-rk3399-v2021.10.5.prod.img
{
    "applicationId": 1867709,
    "deviceType": "rockpi-4b-rk3399",
    ...
}
```
