### ISSUE TITLE
Use a verbose flag to show logs of regular commands

### ISSUE THREAD

**Issue by anujdeshpande** [balena-io/balena-cli#1682]
- **balena CLI version:** e.g. 11.2.1
- **Operating system version:** Ubuntu
- **Install method:** npm 
 **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1

---

Would it make sense to add a `verbose` flag to options to show debug log? For example, when remote logging in, the web auth method doesn't work. In which case setting the verbose tag could show the URL that one needs to open to authorize the login attempt.

**Comment by pdcastro** [comment]
Thanks for the suggestion @anujdeshpande! Some comments:

* In order to show debug logs / output, we don't currently have a flag but you can set the `DEBUG=1` environment variable.

* Some commands already accept a `--verbose` flag, but it has a different meaning to `DEBUG=1`. Generally, `--verbose` means "print additional data" rather than "show the steps that are being taken behind the scenes". For example:

```
$ balena version
11.30.8

$ balena version -v
balena-cli/11.30.8 darwin-x64 node-v12.16.1

$ balena devices supported
SLUG                  NAME
beaglebone-black      BeagleBone Black
beaglebone-green      BeagleBone Green (NEW)

$ balena devices supported -v
SLUG                  ALIASES                ARCH     STATE    NAME
beaglebone-black      beaglebone             armv7hf  RELEASED BeagleBone Black
beaglebone-green                             armv7hf  BETA     BeagleBone Green (NEW)
```

* I like the idea of showing the web auth URL that you raised in #1683. 👍  (Arguably the URL could always be printed, even without DEBUG=1 or `--verbose` being specified.)

* I don't see this issue being actionable in its current generic form. In #1683 it took a specific form (print the web auth URL because it is useful when using the CLI remotely), and I can see someone eventually assigning themselves and working on it. But this issue sounds like going over all the 60+ CLI commands and assessing which "steps behind the scenes" could possibly be useful to print for each of them, and adding conditional logging statements (conditional on DEBUG=1 or similar). I don't see anyone assigning themselves to do that! Instead, I suggest that whenever you came across a specific example of additional verbose or debugging information that would be useful to have for a specific command, with a specific use case, you created an issue / feature request for that. And then if possible, follow it up with a pull request that closes the issue. ;-)
