### ISSUE TITLE
balena login - Web authorization method fails due to IPv4 callback URL when node listens on IPv6

### ISSUE THREAD

**Issue by trinitronx** [balena-io/balena-cli#1765]
- **balena CLI version:** `11.31.18`
- **Operating system version: macOS 10.14.6
- **32/64 bit OS and processor:** `x86_64` `Darwin Kernel Version 18.7.0` on 64-bit 2.6 GHz Intel Core i7
- **Install method:** `npm`
- **Node.js and npm version:** Node `v13.13.0`, npm `6.14.4`

---

After installing `balena-cli` via `npm` and trying `balena login` with "`Web authorization`" method, the web authorization page seems broken.

It wants to use IPv4 callback URL: `https://dashboard.balena-cloud.com/login/cli/http%253A%252F%252F127.0.0.1%253A8989%252Fauth`

The root cause seems to be that `node` is listening on **only `IPv6`**:

```
 sudo lsof -PiTCP -sTCP:LISTEN | grep -i node

COMMAND     PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node      36724    jcuzella   27u  IPv6 0x31435a54b3595b35      0t0  TCP *:8989 (LISTEN)
```

I tried modifying the callback URL manually with URL encoded loopback IPv6 address "`http://[::1]:8989/auth`":

```
perl -MURI::Escape -e "print(uri_escape('http://[::1]:8989/auth'));"
http%3A%2F%2F%5B%3A%3A1%5D%3A8989%2Fauth
```

Giving me this URL: `https://dashboard.balena-cloud.com/login/cli/http%3A%2F%2F%5B%3A%3A1%5D%3A8989%2Fauth`

However, the `dashboard.balena-cloud.com/login/cli/` page just takes me to the default dashboard page, not the one with an **`Authorize`** button.

Seems like maybe `127.0.0.1` IPv4 loopback is hardcoded on the Web UI side, but the `balena-cli` does not specify for `node` to listen on `127.0.0.1:8989` **IPv4**, so it is defaulting to **IPv6** instead!

I was able to complete the authorization manually by opening Google Chrome Developer Console to the `Network` tab, recording the request made to `http://127.0.0.1:8989`, and translating that to cURL using IPv6 `http://[::1]:8989` instead:

```
curl -i -X POST \
   -H "Content-Type:application/x-www-form-urlencoded" \
   -H "Accept-Language:en-US,en;q=0.9" \
   -H "Cache-Control:max-age=0" \
   -H "Connection:keep-alive" \
   -H "DNT:1" \
   -H "Host:[::1]:8989" \
   -H "Origin:null" \
   -H "Sec-Fetch-Dest:document" \
   -H "Sec-Fetch-Mode:navigate" \
   -H "Sec-Fetch-Site:cross-site" \
   -H "Sec-Fetch-User:?1" \
   -H "Upgrade-Insecure-Requests:1" \
   -H "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" \
   -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" \
   -d \
'token=[...SCRUBBED... MY TOKEN WAS HERE ...]' \
 'http://[::1]:8989/auth'
```

**Comment by pdcastro** [comment]
> `$ lsof -PiTCP -sTCP:LISTEN | grep -i node`
> `node      36724    jcuzella   27u  IPv6 0x31435a54b3595b35      0t0  TCP *:8989 (LISTEN)`

Here, also with macOS 10.14.6 and Node 13.13.0, I get:
```
$ lsof -PiTCP -sTCP:LISTEN | grep -i node
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node      52959 paulo   26u  IPv6 0xac63cbcc9941180d      0t0  TCP *:8989 (LISTEN)
```
```
$ netstat -an |grep -i listen
tcp46      0      0  *.8989                 *.*                    LISTEN
```

@trinitronx, the `netstat` output above indicates `tcp46`, so I believe it is listening on both IPv4 and IPv6, on any IP address _including_ `127.0.0.1`.

I have successfully tested `balena login` web authorization with macOS 10.14.6 and Node 13.13.0 / npm 6.14.4, same as your reported versions. I also get the same URL you mentioned, containing `127.0.0.1`:

```
https://dashboard.balena-cloud.com/login/cli/http%253A%252F%252F127.0.0.1%253A8989%252Fauth
```

So I believe the issue you are facing would have some different explanation:
* If you edit your `curl` command and replace `[::1]` with `127.0.0.1`, does it work for you? It works for me. Nice command, by the way! :-)
* Could it be an instance of #1404 ? Sometimes (strangely, not every day) web authorization takes a long time to complete, as a long as a full minute, which is of course a bug (quite high up in the [ordered backlog](https://github.com/balena-io/balena-cli/milestone/2)). As a data point, check if it web authorization completes if you wait about a minute, or even longer.

By the way, thanks to your curl command line, 👍 you have helped narrow down the investigation for issue #1404. While the browser may hang for a minute, the curl command completes web authorization "immediately". (I've added a comment to that issue. I still don't know what the issue is, though...)

**Comment by trinitronx** [comment]
> - If you edit your curl command and replace `[::1]` with `127.0.0.1`, does it work for you? It works for me. Nice command, by the way! :-)

Here is the verbose output from `curl` when I try replacing `[::1]` with `127.0.0.1`:

```
curl -v -i -X POST \
>    -H "Content-Type:application/x-www-form-urlencoded" \
>    -H "Accept-Language:en-US,en;q=0.9" \
>    -H "Cache-Control:max-age=0" \
>    -H "Connection:keep-alive" \
>    -H "DNT:1" \
>    -H "Host:127.0.0.1:8989" \
>    -H "Origin:null" \
>    -H "Sec-Fetch-Dest:document" \
>    -H "Sec-Fetch-Mode:navigate" \
>    -H "Sec-Fetch-Site:cross-site" \
>    -H "Sec-Fetch-User:?1" \
>    -H "Upgrade-Insecure-Requests:1" \
>    -H "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36" \
>    -H "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" \
>    -d \
> 'token=[...SCRUBBED... MY TOKEN WAS HERE ...]' \
>  'http://127.0.0.1:8989/auth'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8989 (#0)
> POST /auth HTTP/1.1
> Host:127.0.0.1:8989
> Content-Type:application/x-www-form-urlencoded
> Accept-Language:en-US,en;q=0.9
> Cache-Control:max-age=0
> Connection:keep-alive
> DNT:1
> Origin:null
> Sec-Fetch-Dest:document
> Sec-Fetch-Mode:navigate
> Sec-Fetch-Site:cross-site
> Sec-Fetch-User:?1
> Upgrade-Insecure-Requests:1
> User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Content-Length: 957
>
* upload completely sent off: 957 out of 957 bytes
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

So it's behaving as if the port is not listening on `127.0.0.1:8989`.  Puzzlingly enough, running the `netstat` command does show both `tcp46`, and `tcp4`:

```
netstat -an | grep -i listen | grep 8989
tcp46      0      0  *.8989                 *.*                    LISTEN
tcp4       0      0  127.0.0.1.8989         *.*                    LISTEN
```

> - Could it be an instance of #1404 ? Sometimes (strangely, not every day) web authorization takes a long time to complete, as a long as a full minute, which is of course a bug (quite high up in the [ordered backlog][1]). As a data point, check if it web authorization completes if you wait about a minute, or even longer.

Based on the description, I'd say it is probably a slightly different issue because I do not see "`a page saying authorization has been granted with a button to go to the dashboard`" as he describes.  The response I see in Google Chrome's Developer Console under the recorded `Network` request is: `(failed)net::ERR_CONNECTION_RESET`

The page looks like this:

<img width="1724" alt="Screen Shot 2020-04-24 at 6 26 08 PM" src="https://user-images.githubusercontent.com/122524/80266455-32c1e280-8659-11ea-8ff7-800d2401a83d.png">


[1]: https://github.com/balena-io/balena-cli/milestone/2

**Comment by pdcastro** [comment]
> Puzzlingly enough, running the netstat command does show both tcp46, and tcp4:
```
netstat -an | grep -i listen | grep 8989
tcp46      0      0  *.8989                 *.*                    LISTEN
tcp4       0      0  127.0.0.1.8989         *.*                    LISTEN
```

This second listen entry for tcp4 `127.0.0.1.8989` is unexpected (at least it doesn't happen for me). I am wondering if it is another unrelated process that happened to be listening on that port already, or perhaps even an old/frozen CLI process left behind. The `lsof` command could help identify the second process (if it is indeed a second process):

```
$ lsof -i :8989
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    54268 paulo   28u  IPv6 0xac63cbcc5bbf860d      0t0  TCP *:sunwebadmins (LISTEN)
```
Here I only get one line while `balena login` is awaiting web authorization, and no lines (no results) if `balena login` is not running. If you have another process listening on port 8989, you may find additional lines, perhaps even results while `balena login` is not running. Then inspect the PIDs with `ps`, for example:
```
$ ps -Af | grep 54268
  501 54351 77521   0  1:06pm ttys004    0:00.00 grep 54268
  501 54268 88290   0  1:04pm ttys006    0:00.97 node /Users/paulo/.nvm/versions/node/v12.16.1/bin/balena login
```
Where `54268` is the PID I got here in the output of `lsof -i :8989`. Try killing the PIDs identified with `kill -9`:
```
$ kill -9 54268
```

Let's see what you find. If it turns out that the problem was indeed another process already listening on port 8989, perhaps an improvement in CLI source code would be for the CLI to use a random unallocated port (and generate the callback URL accordingly) instead of a fixed port number (8989). (There may be a reason why a fixed port number was chosen though... Needs investigation.)

**Comment by trinitronx** [comment]
> This second listen entry for tcp4 127.0.0.1.8989 is unexpected (at least it doesn't happen for me). I am wondering if it is another unrelated process that happened to be listening on that port already, or perhaps even an old/frozen CLI process left behind. The lsof command could help identify the second process (if it is indeed a second process):
>     $ lsof -i :8989
>     COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
>     node    54268 paulo   28u  IPv6 0xac63cbcc5bbf860d      0t0  TCP *:sunwebadmins (LISTEN)

Yeah, looks like there is another process claiming that port:

    lsof -i :8989
    COMMAND    PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
    pCloud    1837 jcuzella   16u  IPv4 0x29fa46b7b3ec2ef5      0t0  TCP localhost:sunwebadmins (LISTEN)

I must not have noticed it due to the `lsof` output on macOS showing the port name `sunwebadmins` instead of `8989`.  It makes sense now.

**Comment by pdcastro** [comment]
Thank you for confirming it @trinitronx. I have created another CLI issue, #1773, to focus on the fact that the CLI fails silently if another process is already listening on port 8989. The CLI should either fail immediately with a clear error message or, perhaps better yet, use a random unallocated port number instead of a fixed port number 8989. I am thus closing this issue in favour of that one, but feel free to add more comments if you need to (I should still get notified even if the issue is closed). Thanks for reporting it.
