### ISSUE TITLE
Application not found (even though it exists)

### ISSUE THREAD

**Issue by alethenorio** [balena-io/balena-cli#1815]
- **balena CLI version:** 11.32.7 - 11.32.15
- **Operating system version:** Ubuntu 20.04
- **32/64 bit OS and processor:** 64-bit Linux on 64-bit Intel processor
- **Install method:** zip

---

There seems to be a bug introduced on balena cli v11.32.7.

I trying to run `balena app <app id>` it returns

```
BalenaApplicationNotFound: Application not found: <app id>

BalenaApplicationNotFound: Application not found: <app id>
```

Running the same command with a version previous to `11.32.7` works well. Also I can see the application in the list of apps when I run `balena apps` (including the latest version).

I have verified this issue with almost every version starting with 11.32.7 until the latest (11.32.15 at the moment)

**Comment by pdcastro** [comment]
Thank you for reporting this issue @alethenorio. A fix PR is under review (#1817), and should be released shortly. The issue was a result of the CLI codebase conversion (from [Capitano](https://github.com/balena-io/capitano/) to [oclif](https://oclif.io/)), and fell through the testing cracks. Capitano used to automatically convert arguments from string to number if they matched a regular expression, and we didn't realise the CLI was relying on this feature for the `balena app` command (and also `app rm`, `app restart`). Sorry for the trouble this has caused you.

**Comment by pdcastro** [comment]
Fixed in CLI release v11.33.2.

**Comment by saveriogzz** [comment]
Hello, sorry to resurrect this old issue but I'm having the same problem with balena-cli version 13.3.1 .
When running `balena fleet restart someorg/somefleet`, I get the error `BalenaApplicationNotFound: Application not found: 7`

**Comment by MateuszKrazek** [comment]
> I started to have the same problem on v18.0.0 -> is was working fine ~two months ago, but suddenly my pipeline started to fail and gives me Application not found, even though it exists in Balena Portal. Were there any changes or sth?
> 
> ![Image](https://github.com/user-attachments/assets/a690fb7b-01e7-4ab2-b6a7-c0ac82b01165)

Instead of deleting, gonna reply with what solved my problem: 

in my pipeline, I ofc  have: 
`balena login --token "$balena_token"`

before ` balena deploy ....`

in my example, this token is stored in Bitbucket and simply got expired - had to generate new via Balena Portal and update the secret in bitbucket. Case Closed.
