### ISSUE TITLE
Unknown error while using Balena push to device in local mode

### ISSUE THREAD

**Issue by jgentes** [balena-io/balena-cli#1861]
# Expected Behavior

`Balena push` should push code to local mode device.

# Actual Behavior

```
PS C:\dev> balena scan
Reporting scan results
-
  host:          b2b1217.local
  address:       192.168.86.129
  dockerInfo:
    Containers:        1
    ContainersRunning: 1
    ContainersPaused:  0
    ContainersStopped: 0
    Images:            5
    Driver:            aufs
    SystemTime:        2020-06-08T18:30:00.888568077Z
    KernelVersion:     5.2.10-yocto-standard
    OperatingSystem:   balenaOS 2.50.1+rev1
    Architecture:      x86_64
  dockerVersion:
    Version:    18.09.17-dev
    ApiVersion: 1.39

PS C:\dev> balena push b2b1217.local --debug
[debug] Using . as build source
[Debug]   Checking we can access device
[Debug]   Sending request to http://192.168.86.129:48484/ping
[Debug]   Checking device version: 11.4.10
[Info]    Starting build on device 192.168.86.129
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "."
[Debug]   Creating project...
[Debug]   Tarring all non-ignored files...
UNKNOWN: UNKNOWN: unknown error, stat 'C:\dev\node_modules\.bin\esparse'

Error: UNKNOWN: unknown error, stat 'C:\dev\node_modules\.bin\esparse'
```

# Steps to Reproduce the Problem

The balena forum has the docker-compose and dockerfile used. A few additional notes:

- My dev environment is Windows Subsystem for Linux
- Docker does not run in WSL, so I run docker for Windows and use balena-cli through powershell

# Specifications

- **balena CLI version:**
balena-cli version "11.35.18"
Node.js version "10.19.0"

- **Operating system version:** 
Windows 10

- **32/64 bit OS and processor:**
64-bit Intel (SurfaceBook Pro)

- **Install method:** 
Executable installer, run through powershell

# Additional References

https://forums.balena.io/t/balena-local-push-fails-with-unknown-error-esparse/126174/22

Device I am pushing to: https://dashboard.balena-cloud.com/devices/b2b1217ac221b196009d00a31cf9270b/summary

**Comment by pdcastro** [comment]
> Install method: Executable installer, run through powershell
> My dev environment is Windows Subsystem for Linux

I am not sure I understand this combination: are you saying that your project runs on Linux / WSL? Perhaps you run `npm install` on WSL, and the folder `'C:\dev\node_modules'` is generated on WSL, and then you run `balena push` on PowerShell -- is this what's happening?

The debug output suggests that the error is thrown when the CLI attempts to read the files from the current directory (`C:\dev`), in particular file `'C:\dev\node_modules\.bin\esparse'` which belongs to your project. Can you list that file on the command line or with Windows Explorer? Is there anything unusual or special about that file? Could it be that it was generated on WSL as a soft link that WSL understands, but PowerShell does not? The CLI for Windows may not understand the WSL soft links.

Some thoughts:

* Generally it is preferable to use a CLI release for Linux on WSL/bash, if your development environment is WSL/bash. But you can have two CLI installations simultaneously, Windows and WSL/Linux, and use either or both as convenient.

* You can also configure WSL to use Docker Desktop for Windows -- no need to install Docker within the WSL environment. This this FAQ entry for more details: ["Docker seems to be unavailable" error when using Windows Subsystem for Linux (WSL)](https://github.com/balena-io/balena-cli/blob/master/TROUBLESHOOTING.md#docker-seems-to-be-unavailable-error-when-using-windows-subsystem-for-linux-wsl)

* The `balena push` command specifically (for either a local device or the balenaCloud builders) does not require Docker, so you may attempt using a CLI release for Linux (standalone zip file for Linux) on a WSL bash shell, instead of using the executable installer for Windows on PowerShell. 
  * I have just tested `balena push <ip-address>` on WSL with a CLI release for Linux (standalone zip file for v11.35.18) and it was successful.

* If that file (`'C:\dev\node_modules\.bin\esparse'`) was a soft link and not actually essential for running your project with `balena push`, you could try deleting it on WSL. It might be enough to avoid the CLI error on PowerShell.

* If all else fails, try deleting the folder `C:\dev\node_modules` and re-creating it (presumably with `npm install`, or the way you would normally re-create it for your project).

**Comment by jgentes** [comment]
Thanks @pdcastro, I didn't realize docker wasn't required. I must have been thinking of `balena preload`.

I installed balena-cli in WSL and tried to push from there and it worked, so I think your suggestion was correct.. running `balena push` from powershell when my dev environment is in WSL caused issues for some reason, even though the mount point (`/mnt/c/dev`) was the same as the local directory (`c:\dev`) that I was running the command from.

Thanks for your help!
