### ISSUE TITLE
Get 65200 illegal hardware instruction when running balena cli commands and the device is in local mode

### ISSUE THREAD

**Issue by aifreedom** [balena-io/balena-cli#1878]
# Expected Behavior

When the device is in local mode, I expect I can push image to it with `balena push <device_id>.local`.

# Actual Behavior
See the error in this gist https://gist.github.com/aifreedom/ed715dcf6643ce54fa6c6048eb9d9bc3

The same command can work if the device is not in local mode. 

# Steps to Reproduce the Problem

1. Put the device (mine is a Raspberry 4) in local mode
1. Run `balena push <device_id>.local` from an image I'm working on
1. See the error above. The error also shows when I run other balena commands, like `balena logs <device_id>.local --system`

# Specifications

- **balena CLI version:** balena-cli version "12.1.3"
- **Operating system version:** macOS 10.15.5
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** , Node.js version "14.4.0", npm version "6.14.5"

**Comment by pdcastro** [comment]
Thanks for this report @aifreedom. 👍  I wonder if it is the same issue as #1847 - Node.js v14 is not yet fully supported. Does the error happen with Node.js v12? You can also try the graphical installer for macOS or the standalone zip file, which bundle their own Node.js interpreter. Instructions at: https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

**Comment by aifreedom** [comment]
@pdcastro Sorry for late reply. It works without problem with Node.js v12.

**Comment by pdcastro** [comment]
`balena push` now works with Node.js v14 -- since balena CLI version 12.9.0, I believe (just tested with CLI v12.14.4). Therefore I am closing this issue -- but feel free to add comments as needed.

Note however that, for now, the officially supported Node.js versions are still 10 and 12 ([as documented](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md)) because other CLI commands like `os configure` still don't work with Node.js v14 (issue #1990).

Thanks again for reporting this issue! 👍
