### ISSUE TITLE
Allow setting `release_version` during a deploy/push operation

### ISSUE THREAD

**Issue by xginn8** [balena-io/balena-cli#1908]
We now support setting a unique `release_version` property per release. We should allow that to be set during a `deploy`/`push` operation (and any others I may have missed), perhaps behind a flag?

related to https://github.com/balena-io/balena-io/issues/2219 and https://github.com/balena-io/balena-api/issues/2655

**Comment by pdcastro** [comment]
Connects to:
* #892 Add 'balena push' flag to specify a release tag
* #1356 Successful balena deploy reports release commit rather than release id

**Comment by pdcastro** [comment]
PR #2193 was closed without merging because (as I understand it) the following discussion concluded that the release version should be specified through of a contract file:
https://www.flowdock.com/app/rulemotion/resin-tech/threads/sxmoCgQkKE9-OPuJtf2tHnX--rf

The contract file being:
https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/#balenayml-configuration-file

In the case of `balena push`, I believe the contract file is parsed by the balenaCloud builder. In the case of `balena deploy`, I believe it depends on issue #2183 [`balena deploy` should parse, validate, and create a contract as part of the release it creates](https://github.com/balena-io/balena-cli/issues/2183) being implemented.

**Comment by pdcastro** [comment]
Connects to JF Product Improvement: [Draft releases and release versioning](https://jel.ly.fish/8ea1c390-9a85-402d-978c-4d31dcb0d235) (restricted access)

**Comment by pdcastro** [comment]
By the way, at the API data model level, I hear that the `release.release_version` field is now deprecated in favor of `release.semver`. The balenaCloud web dashboard will present the value of `release.semver`.
Ref.: [FD thread](https://www.flowdock.com/app/rulemotion/public-s-community/threads/Rr7rfak-9UuJTTemEco2Klg_yaO) (restricted access)

**Comment by pdcastro** [comment]
Closing this issue in favour of #2183 with regard to `balena deploy`. For `balena push` (cloud, not local mode), this feature is already implemented by the balenaCloud builder. The builder will set either the `release.semver` field or the `release.release_version` field of the release object (API model) (see [balena-builder PR 892](https://github.com/balena-io/balena-builder/pull/892) (restricted access)), depending on whether the `version` field in the [balena.yml contract file](https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/#balenayml-configuration-file) looks like a [semver](https://semver.org/) by regex matching.
