### ISSUE TITLE
nocache parameter is ignored in some cases

### ISSUE THREAD

**Issue by karaxuna** [balena-io/balena-cli#1955]
# Expected Behavior

Should consider `nocache` parameter when running:

```
balena build -a <my-app> ./source --nocache
```

# Actual Behavior

It still uses cache.

# Specifications

- **balena CLI version:** v12.5.0

**Comment by pdcastro** [comment]
Checking the original thread (forum: https://forums.balena.io/t/build-deploy-app/156127/27), the issue was that the position of boolean flags on the command line used to matter:

* OK: `balena build -a <my-app> ./source --nocache`
* Not OK: `balena build -a <my-app> --nocache ./source`

This was fixed in CLI v12.9.9 by migrating the parser from Capitano to oclif, with some further fixes in CLI v12.14.10.
