### ISSUE TITLE
`balena scan` sudo issue

### ISSUE THREAD

**Issue by frederikheld** [balena-io/balena-cli#2149]
System is Ubuntu 20.04 (64 Bit)
balena-cli version is 12.36.1

(the issue exists with balena-cli v12.40.2 on Ubuntu 20.10 (64 Bit) as well)

When I run `$ balena scan` as described in the [balena-cli master class](https://www.balena.io/docs/learn/more/masterclasses/cli-masterclass/), I get the message "You need root/admin privileges to run this command". So I run `$ sudo balena scan`, which gives me the following message "sudo: balena: command not found".

This is very odd. What am I doing wrong?

Full terminal output:
```sh
frederik@mycomputer:~$ balena scan
You need root/admin privileges to run this command

frederik@mycomputer:~$ sudo balena scan
[sudo] password for frederik: 
sudo: balena: command not found
frederik@mycomputer:~$ balena version -a
balena-cli version "12.36.1"
Node.js version "12.18.1"
frederik@mycomputer:~$ whereis balena
balena: /opt/balena-cli/balena
```
Installed via zip package as described [here](https://github.com/balena-io/balena-cli/blob/master/INSTALL-LINUX.md). Instead of adding the extracted path to $PATH, I copied it to `/opt/balena-cli` and added `export PATH="$PATH:/opt/balena-cli"
` to `~/.bashrc`. I came to the decision to to do it this way after reading a lot about the history of linux file system and install paths. But I'm not an expert about what side-effects this choice might have. So may this cause the issue?

In an attempt to fix this, I uninstalled `balena-cli` and tried to install it via npm as described [here](https://github.com/balena-io/balena-cli/blob/master/INSTALL-ADVANCED.md), but it failed with a long list of warnings and errors:

```sh
frederik@mycomputer:~$ sudo rm -r /opt/balena-cli
frederik@mycomputer:~$ sudo npm install balena-cli -g --unsafe-perm --production
[...]
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/es-abstract-f6c79366/helpers/maxSafeInteger.js'
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/es-abstract-f6c79366/2015/MinFromTime.js'
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/balena-io-modules/unbzip2-stream.git /root/.npm/_cacache/tmp/git-clone-74700e65/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-74700e65/.git'
npm ERR! 
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/es-abstract-f6c79366/2016/MinFromTime.js'
[...]
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/@balena.io/usb-e0a0f77c/libusb/PORTING'
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/@balena.io/usb-e0a0f77c/libusb/README'
npm WARN tar ENOENT: no such file or directory, open '/usr/lib/node_modules/.staging/node-raspberrypi-usbboot-149a319a/blobs/kernel7.img'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-01T23_10_05_195Z-debug.log
```

What would be the correct way to install `balena-cli` on Ubuntu to be able to use `balena scan`?

**Comment by frederikheld** [comment]
I just tried another approach that is closer what is in the docs. I also used the version that was released 4 days ago.

Same issue with `$ sudo balena scan`.

```sh
frederik@mycomputer:~/temp$ unzip balena-cli-v12.37.0-linux-x64-standalone.zip 
Archive:  balena-cli-v12.37.0-linux-x64-standalone.zip
   [...]
frederik@mycomputer:~/temp$ ls ~/balena-cli
balena      drivelist  ffi-napi     mountutils  resin-image-fs  xdg-open-402
@balena.io  ext2fs     lzma-native  ref-napi    xdg-open        xxhash
frederik@mycomputer:~/temp$ cd ~
frederik@mycomputer:~$ export PATH=$PATH:/home/frederik/temp/balena-cli
frederik@mycomputer:~$ balena --version
12.37.0
frederik@mycomputer:~$ balena scan
You need root/admin privileges to run this command

frederik@mycomputer:~$ sudo balena scan
sudo: balena: command not found
frederik@mycomputer:~$ 
```

**Comment by frederikheld** [comment]
Finally I found the solution: https://itectec.com/ubuntu/ubuntu-cant-sudo-find-a-command-after-i-added-it-to-path/

Had to add the path `/opt/balena-cli` to the sudo path as well.

```sh
sudo visudo
```

Add `:/opt/balena-cli` to `secure_path`.

It would help to have this in the documentation. If someone can confirm that I'm doing this right, I would submit a PR that adds this information to the docs.

**Comment by pdcastro** [comment]
@frederikheld, thank you for raising this issue, finding a solution and offering to document it! 🙏  (It's the best kind of issue report!) 😁  I think editing the `sudoers` file, `secure_path` variable, is a good solution and worth documenting. 👍   

To put it in context, there are likely other arguably better solutions (and I see you have already spotted them in PR #2148, in a comment reaction), but which require more development work:

1. As per issue #542, ideally we would remove the need for superuser privileges (so that `balena scan` runs as an unprivileged user). It may be possible, but requires further understanding of Hedss comment: _"[...] it requires balena-cli to be run using sudo when there are other instances (as 224.0.0.251:5353 needs to be shared)"_
2. Failing that, as per issue  #1714, the CLI could dynamically escalate privileges when the need is detected, raising a privilege popup (GUI) or password prompt on the command line.
3. Failing that, when `balena scan` is executed a non-root user, the CLI could dynamically detect this and also detect whether a `sudoers` file exists. If it exists, the CLI could print a hint along the lines of _"be sure to add XXX to the `secure_path` variable in the '/etc/sudoers' file",_ where XXX is replaced by the CLI's actual path detected at runtime.
4. Failing that, we could add Linux installation instructions asking users to edit the `sudoers` file. We could also add a note to the output of `balena help scan`.

If you would like go ahead with option 4 (which would definitely be an improvement over the status quo of letting users figure out by themselves what to do when faced with `sudo: balena: command not found`), I would suggest a discrete note under the `balena scan` section of the following document:
https://github.com/balena-io/balena-cli/blob/master/INSTALL-LINUX.md#balena-scan
(In addition to a note in the output of `balena help scan`.)

We should keep in mind that the CLI should be compatible with Linux distros like Alpine, Ubuntu, Debian, Arch Linux, etc. Alpine in particular would be good to test too (does the same problem and solution apply to Alpine?). I'd then suggest a generic statement like _"Edit the `/etc/sudoers` file"_ instead of _"Run `sudo visudo`"_ because the latter makes `visudo` an additional dependency that needs installing, and presumably `visudo` uses `vi` as the editor and many users may not be comfortable with using the `vi` shortcuts (they may prefer other editors like 'nano' or a GUI text editor).

Thank you again! 🙏

**Comment by frederikheld** [comment]
Hey @pdcastro, thanks for the kind reply :-) And I have to apologize for the belated answer.

I did some research on your proposed solution. A comment on top of `/etc/sudoers` says "This file MUST be edited with the 'visudo' command as root." Tutorials on the internet also strongly advise to not edit it via a normal text editor. I guess `visudo` does some additional action in the background apart from editing the file. On the plus side, this seems to imply, that wherever there's a `/etc/sudoers` file, there should also be `visudo` available :-) So I'm gonna us this approach in the docs. I'll submit a PR soon.

**Comment by frederikheld** [comment]
I checked the docs of the distros you mentioned if they come with `visudo`:

[v] Alpine --> https://docs.alpinelinux.org/user-handbook/0.1a/Working/post-install.html
[v] Ubuntu --> I tried myself on 20.04
[v] Debian --> https://wiki.debian.org/sudo
[v] Arch --> https://wiki.archlinux.org/index.php/sudo#Using_visudo

However, I could only test it on Ubuntu 20.04.

**Comment by frederikheld** [comment]
What kind of comment do you have in mind for  `balena help scan`? Something like this?

```
`balena scan` requires sudo privileges on linux, which needs to be configured after installation. Please read `INSTALL-LINUX.md` for more information.
```

I tried to get the tests running, but without luck. They always fail with `NockMock: Unexpected HTTP request: POST https://sentry.io:443/api/149239/store/`. Might be related to the fact that I tried to run them in a Docker container to match the Node version.

Any hints how I could get past this?

**Comment by pdcastro** [comment]
@frederikheld, I think it will be easier if you create a pull request with what you've got at the moment, even if tests are failing. I could then pull the branch and try running the tests on my laptop too, for debugging. I also have suggestions on a different note for `balena help scan`, but I'd like to see the proposed changes to the INSTALL.md in the PR before making a precise suggestion. :-)

(Superuser privileges are actually required on all platforms - Windows, Mac, Linux. On Windows it takes the shape of selecting "run as an administrator" through the GUI, while on macOS and Linux, it requires using `sudo`. But the editing of the `sudoers` file is only needed on Linux I believe.)

**Comment by frederikheld** [comment]
I'm sorry for not getting back to this for a long time.

Today I installed `balena-cli` on a new computer, so this became relevant again. I just submitted #2206 with my current changes (just an addition to INSTALL-LINUX.md).

Some notes about that: I tried to do it in the style of the rest of your docs. But I don't really like it as it is very unspecific about what _actually_ needs to be done. The whole installation process is "read this", "read that" and you have to go down into rabbit holes about where additional packages should be installed an where path variables should be set. This is a high bar for users that don't understand much about the history of linux.

But if you go down the rabbit hole, you learn, that there's a lot of opinions about whether `/opt` or `/var` or any of it's sub-directories is the right one to install additional software. And they all boil down to "if we do it by design, there's only one correct answer" but everyone has a different design in mind, depending on their own history in the Linux world and the actual reality is, that all of those different designs have emerged to chaos and it really doesn't matter which directory you choose.

The same goes for `.bashrc` vs. other options to set PATH.

Bottom line: It would be much easier for the average user to install `balena-cli`, if we would show one way to do it. For those who are interested in the details we can still link to external sources that explain the details but everyone who has a strong opinion about such details most probably already has their way to do stuff.

After reading all those discussions, I came up with this set of instructions for myself:

1. Download zip archive from here. Look for the "*-linux-x64-standalone.zip"
2. Unpack the archive
3. Copy the `balena-cli` folder to `/opt`. There should now be `/opt/balena-cli`.
4. Add `/opt/balena-cli` to your PATH by adding `export PATH="$PATH:/opt/balena-cli"` as a new line at the bottom of your `~/.bashrc" file
5. Activate the new PATH by running `$ source ~/.bashrc`
6. Check if it's working by running `$ balena --version`
6. To be able to run `$ sudo balena-cli`, run `$ visudo` and add `:/opt/balena-cli` to the `secure_path` variable.
6. Check if it's working by running `$ sudo balena`

This is much more straightforward to follow than the one I submitted in the PR. But of course it is less general.

Another small thing: To distinguish between commands and names/paths, I prefer to put the `$` in front of commands. I didn't do that in the docs either because it doesn't seem to be the style of the docs, but I think it would help to do so.

For the hint in the `balena` comand I didn't know where to put it and didn't have enough time to get the setup running :-P sry...

**Comment by frederikheld** [comment]
The most user-friendly way on Ubuntu would be `$ sudo apt install balena-cli` or `$ sudo snap install balena-cli` though. Do you plan to provide package sources to install balena-cli via common package managers?

**Comment by frederikheld** [comment]
I just found #1711. Yes, it would be great to have it simplified! And I just found a new issue with sudo and installation in general. I added it as comments there.

**Comment by pdcastro** [comment]
Connects-to: #477, #385, #542, #550, #572, #940, #1444, #1714, #2062, #2101

**Comment by pdcastro** [comment]
> This is much more straightforward to follow than the one I submitted in the PR. But of course it is less generic.

I agree! It's always a balance with between straightforward for a particular scenario and generic for multiple scenarios. The CLI's standalone zip package is also used in Docker containers and users' CI environments where there is no windowing system, no user accounts -- only `root` -- and no need for `sudo` (`sudo` may not even be installed / available).

You will have seen that I created PR #2208 where I am suggesting `/home/james/balena-cli` instead of `/opt/balena-cli`. Personally I also like `/opt/balena-cli` better, but I understand that `/opt` is usually owned by the root user and:

* If `/opt/balena-cli` had `root` permissions but the CLI was then executed as a non-root user, the CLI would not be able to create or update `/opt/balena-cli/.fast-boot.json`, with the consequence of running a bit slower.
* Users following the instructions would be more likely to get into trouble with the need for changing permissions and using `sudo`, e.g.
```
sudo mkdir /opt
sudo cp *-linux-x64-standalone.zip /opt
cd /opt
sudo unzip balena-cli-v12.40.3-linux-x64-standalone.zip
```
and then maybe:
```
cd /opt
sudo chown -R james:staff balena-cli
```
To avoid all this `sudo` and `chown`, I thought it would be easier to mention `/home/james/balena-cli`, then it's all non-root. And if someone is installing the CLI in a container where only `root` is available, hopefully they'd figured they could use `/root/balena-cli` and the rest is the same.

> I prefer to put the `$` in front of commands

I also like it and we actually had `$` in several places in documents, but then we deleted it because some users were typing the `$` on command line and getting errors. :-/

**Comment by frederikheld** [comment]
Ok, I understand that the sudo issue can be avoided by installing balena-cli into a non-root directory. Right now the docs don't give any hint on that, so #2208 will be an improvement. I would not suggest `/home/james/balena-cli` though but `/home/james/.balena-cli` instead. Right now I'm on a very fresh system and it's so much better to have a clean home directory. I know that a lot of apps will start to clutter it, but as long as they respect the "hidden directory" convention, it's tolerable because I can still easily find my stuff. I'm not really happy about the idea to install balena-cli to the in general (I don't think that it's a good idea to install anything into the home directory, it's for user files and user configs), but it's a good workaround to avoid the error. The best fix for this issue as well as for the need to document more details would be to provide installers ;-) I'm really looking forward for that :-)

Thanks for the hint that I need to configure Docker to run without sudo to avoid problems with balena-cli. Since I'm using Docker I can't wrap my head around the question if having a docker user that has almost sudo permissions is better than just running docker with sudo... :-P

"but then we deleted it because some users were typing the $ on command line and getting errors. :-/" rly? :-D omg :-D Do their command prompts not have the dollar sign? Another way that helps to separate commands from paths and stuff is to put them in a separate line. But this can make the docs very long...

**Comment by PackElend** [comment]
Hi,
running into the same issue.
Does it apply for WSL 2 as well?

`Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/usr_name/.nvm/versions/node/v12.22.9/bin/balena"`

as I still get the error


```
$ whereis balena
balena: /home/usr_name/.nvm/versions/node/v12.22.9/bin/balena
$ balena version -a
balena-cli version "13.1.10"
Node.js version "12.22.9"
```

**Comment by pdcastro** [comment]
@PackElend, I think (not 100% sure) that `secure_path` needs to be a list of _folders_ rather than _files:_

**Folder:** `/home/usr_name/.nvm/versions/node/v12.22.9/bin`
**File:** `/home/usr_name/.nvm/versions/node/v12.22.9/bin/balena`

So try using the folder rather than the file as shown above.

> I still get the error

What exactly is the error? Is it `sudo: balena: command not found`?

**Comment by PackElend** [comment]
> **Folder:** `/home/usr_name/.nvm/versions/node/v12.22.9/bin`
> **File:** `/home/usr_name/.nvm/versions/node/v12.22.9/bin/balena`

that fixes it
`$: sudo balena scan `
is working now but it looks like it is not really usable only if start playing around with Windows Firewall as WSL2 is NAT'ted, see e.g. https://develmonk.com/2021/06/05/easiest-wsl2-bridge-network-without-hyper-v-virtual-network-manager/ or https://github.com/microsoft/WSL/issues/4150#issuecomment-504209723.
Even if it is off-topic here, is there any manual how to set FW rules for `balena scan`?

**Comment by pdcastro** [comment]
@PackElend, there is no manual to setup WSL2 firewall rules for `balena scan`, but your contribution would be very welcome if you would to write some instructions. `balena scan` uses [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS) that involves multicast UDP packets (as I understand it), so it is possible that it would require a fully bridged network interface -- e.g. either sharing the host OS physical network interface (same IP address as the host OS), or a network interface with its own IP address but part of the same subnet as the host OS (not behind WSL2 NAT).

Something else I could recommend is to additionally install the "native" balena CLI for Windows using the `.exe` graphical installer (it is OK to have both a WSL installation and a native installation) and execute `balena scan` in a PowerShell or cmd.exe prompt that was started with administrator privileges (Start Menu -> Type PowerShell -> Right click PowerShell -> Select "Run as administrator").

**Comment by PackElend** [comment]
> so it is possible that it would require a fully bridged network interface

I'm afraid of this, to get is tested would properly quite time-consuming



> install the "native" balena CLI for Windows using

I did that in the first step but it cannot run 
balena-io-playground/ssh-key-insert: Tooling to insert the relevant SSH keys into balena devices’ configuration. (github.com) so I started with WSL.
Background is https://forums.balena.io/t/add-ssh-key-after-provisioning-to-production-device/350886/
Let me write down my how-to for WSL afterwards I open another ticket to continue this here

**Comment by PackElend** [comment]
@pdcastro, see #2449
