### ISSUE TITLE
Cannot push wifi-repeater-master to my application

### ISSUE THREAD

**Issue by TJQuin** [balena-io/balena-cli#2164]
I am using a raspberry pi 3B+ and following a tutorial on the balena.io page for making a wifi repeater.  I got to the part in which I am supposed to push the code that I got from GitHub to my application.  I am not sure if I have the code in the wrong place or what but I have the unzipped folder, wifi-repeater-master, inside the balena-cli folder.  I then go into the balena-cli folder through the command prompt on my windows 10 computer, use balena login, which seems to work and then try balena push Wifi_Repeater (which is my AppName) and I this comes up:
[Error]    Could not detect project type: Service main: Could not find a Dockerfile for this service
[Error]    Not deploying release.
Remote build failed

If anyone could help fix this that would be great.  I'm sure it's just something I missed but I can't find it anywhere or figure it out with the few things I tried.

**Comment by pdcastro** [comment]
> following a tutorial on the balena.io page

@TJQuin, do you mean this page? - https://github.com/balenalabs-incubator/wifi-repeater

> I have the unzipped folder, wifi-repeater-master, inside the balena-cli folder

Instead of unzipping inside the balena-cli folder, unzip it elsewhere - for example in the Downloads folder, or on your "homedir" (Users folder) - anywhere but not inside the `balena-cli` folder. :-)

By the way, the balena CLI installation instructions are at: https://github.com/balena-io/balena-cli/blob/master/INSTALL.md
When correctly installed, the `balena` command can be used in any folder.

Then go into the `wifi-repeater-master` folder, and try the `push` command again.

For additional help, I suggest asking in the balena forums, which are monitored by balena's support team and the wider user community: https://forums.balena.io/c/project-help/12

**Comment by TJQuin** [comment]
I was following this page - https://www.balena.io/blog/turn-a-raspberry-pi-into-a-wi-fi-access-point-or-repeater/ 
It did not have anything about the balena CLI installation so I was trying to figure that out myself.  I will follow the balena CLI instruction that you linked and hopefully it'll work.  Thanks!

**Comment by TJQuin** [comment]
It worked. Thanks!
