### ISSUE TITLE
Bug: Windows 10 local flash hangs "sometimes"

### ISSUE THREAD

**Issue by LeFish1** [balena-io/balena-cli#2202]
# Expected Behavior

I am wanting to run `.\balena.exe local flash "C:\image.img" --yes --drive \\.\PhysicalDrive1` to flash a locally stored 16GB image.

# Actual Behavior

Using Windows Powershell with admin credentials.
At some random percentage the flashing process hangs. After pressing some button (either keyboard or mouse) the flashing process continues and finally sucessfully finishes.

# Steps to Reproduce the Problem

Running Windows 10 Build 19042

Windows PowerShell
`PS C:\WINDOWS\system32> cd C:\Users\myname\Desktop\somefolder\Runtime\res\balena-cli

PS C:\Users\myname\Desktop\somefolder\Runtime\res\balena-cli> .\balena.exe local flash "C:\Users\myname\Desktop\somefolder\Runtime\res\somefolder\Raspi.img" --yes --drive \\.\PhysicalDrive1

Flashing [========================] 100% eta 0s
Validating [========================] 100% eta 0s`

Stopped at around 52%, only pressed right, then left Mouse button -> finished sucessfully.

# Specifications

I experience the same behaviour with etcher.exe v1.1.2 - maybe it is my system?

Thanks!

Best regards
LeFish

**Comment by pdcastro** [comment]
> At some random percentage the flashing process hangs. After pressing some button (either keyboard or mouse) the flashing process continues and finally successfully finishes.

How strange! It reminds me of an old Epson scanner I had, with an old version of the Epson Scan software. Sometimes the scan would pause and would only resume if I moved the mouse cursor (anywhere on the screen, even outside the app window). Perhaps the fix is for us to write another tool that automatically moves the mouse cursor and randomly clicks on things! ***just kidding*** 😁 

> I experience the same behaviour with etcher.exe v1.1.2 - maybe it is my system?

This is useful information, 👍  because the balena CLI uses the [Etcher SDK](https://www.npmjs.com/package/etcher-sdk):
https://github.com/balena-io/balena-cli/blob/v12.40.2/lib/commands/local/flash.ts#L28

But `etcher.exe` v1.1.2 is 3.5 years old! I am looking here:
https://github.com/balena-io/etcher/blob/master/CHANGELOG.md

Could you try updating Etcher (`etcher.exe`) to the latest version, and check if Etcher has fixed this? You can get the latest version here: https://www.balena.io/etcher/

Currently the balena CLI is also using an old version of `etcher-sdk`, v2.0.20, but it's "only" 1 year old rather than 3.5 years old. :-) @mbalamat is working on updating it to the latest version in PR #2168 / issue #2079.

**Comment by LeFish1** [comment]
> Could you try updating Etcher (`etcher.exe`) to the latest version, and check if Etcher has fixed this? You can get the latest version here: https://www.balena.io/etcher/
As far as I am aware of, Etcher dropped its integrated CLI some versions ago.
But newer versions have a known problem on windows machines: [https://github.com/balena-io/etcher/issues/2274](url)
Therefore I endend up using this very old version.

Regarding this issue: I mass-flashed 20-some images with balena-cli these days. Always 5#-patches at the same time using c++ concurrency::parallel_for_each.
And I never experienced this stalling anymore.
It even works silently now as I am pushing the output to > NUL

So maybe the issue was really on my side.

I will flash more images the next days/weeks.

As of now this bug can be closed.

Thanks!
