### ISSUE TITLE
balena ssh: Remove unneeded communication with the API when using local mode

### ISSUE THREAD

**Issue by rmorillo24** [balena-io/balena-cli#2372]
# Expected Behavior

when working in local mode with a device, doing `balena ssh` should work always when using a local network, even when there is no connection with balenaCloud.
I would expect local mode to work independently from the cloud, either because there is a firewall, or API unavailability.

# Actual Behavior

When we've experienced balenaCloud API outages, `balena ssh` would not work, not connecting to the device or returning any error. 

# Steps to Reproduce the Problem
With an API outage, balena ssh doesn´t work.
I´ve tried disconnecting the router from internet, and it does connect, but when I exit the session it remains waiting .

# Specifications

- **balena CLI version:** e.g. 1.2.3 (output of the `"balena version -a"` command)
- **Cloud backend: openBalena or balenaCloud?** If unsure, it will be balenaCloud
- **Operating system version:** e.g. Windows 10, Ubuntu 18.04, macOS 10.14.5
- **32/64 bit OS and processor:** e.g. 32-bit Windows on 64-bit Intel processor
- **Install method:** npm or zip package or executable installer
- **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1

# Additional References

If applicable, please add additional links to GitHub projects, forums.balena.io threads,
gist.github.com, Google Drive attachments, etc.

**Comment by srlowe** [comment]
@rmorillo24 Thanks for creating the issue.  

Just to clarify, 

> I´ve tried disconnecting the router from internet, and it does connect, but when I exit the session it remains waiting .

So now when you try without an internet connection, you can connect to local device via SSH?  (but the CLI doesn't return control of the command line afterwards?) 

 Just asking because this seems different to the symptoms you describe during the API outage:

> When we've experienced balenaCloud API outages, balena ssh would not work, not connecting to the device or returning any error.

So are you saying that the behaviour was different in the API outage and your simulated test (disconnected router)? 

I'll do some tests of my own now.

**Comment by rmorillo24** [comment]
That is correct @srlowe 
While writing down the issue, I went to reproduce by disconnecting the router, and found the different behavior in nboth situations.
They are different symptoms, and I guess that an API outage is behaving differently than what I tried: it might be establishing the connection, but not having a response. In the use case I reproduced there can't be a connection at all. Thus the difference in behavior.

**Comment by pdcastro** [comment]
CLI v12.53.3 addresses this issue in a couple of different ways / scenarios.

What we found tricky was that, even though some commands like `balena ssh <ip-address>` do not require an internet connection for the operation of the command itself, the CLI will still "optionally" use the internet (if it can), in order to:

* Occasionally (no more than once a day) query the npm registry to check for new versions of the CLI, and to enforce its deprecation policy.
* Submit minimal usage stats/analytics to balenaCloud (see [Data collected by balena](https://www.balena.io/docs/learn/more/collected-data/)), to allow us to determine what commands are popular or causing platform instability, especially in the event of bugs in either our software or user's software (e.g. some CLI command hammering the API database). 
* In case of unhandled errors that cause the CLI to crash, to report it to us through Sentry.io.

You would think it would be easy to detect whether or not an internet connection is available for optional use, and some cases it is, but in other cases it is not:

Easy and quick:
* The workstation's network interfaces (WiFi, Ethernet) are all down.
* A router does not have a route to the internet and immediately errors with a fatal "no route to host" error.
* A hostname does not exist and DNS immediately answers "not found"

In these cases, `balena ssh <ip-addr>` will work fine "without a connection to the internet".

Not so easy:
The workstation has an internet connection, but:
* It is filtered by some local network firewall that selectively drops packets, for example in air-gapped manufacturing environment.
* A balenaCloud API outage where API requests (including analytics reporting) times out.
* It is unstable at the user's end, be it a weak WiFi link or an intermittent Internet Service Provider issue.

In these cases, the CLI in principle relies on timeouts that could be described by users as _"but when I exit the ssh session it remains waiting."_ Before CLI v12.53.3, the timeout was a system default of 120 seconds if I am not mistaken, and with v12.53.3 it was reduced to 4 seconds.

In addition, starting with CLI v12.53.3, if the 4s timeout is reached for analytics, the CLI will print the following hint to the console:

```
Timeout submitting analytics event to balenaCloud/openBalena.
If you are using the balena CLI in an air-gapped environment with a filtered
internet connection, set the BALENARC_OFFLINE_MODE=1 environment variable
when using CLI commands that do not strictly require access to balenaCloud.
```

Setting `BALENARC_OFFLINE_MODE=1` will prevent the CLI from checking for new versions, reporting unhandled errors, sending analytics data and enforcing the deprecation policy, and therefore will avoid any timeouts, but it will also prevent the execution of commands that require an internet connection such as `balena push` or `balena ssh <UUID>` for ssh via the balenaCloud VPN.
