### ISSUE TITLE
Should offer standalone armv7hf and arm64 builds

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-cli#2554]
Even though `npm i` does work on arm systems now, we should also be offering standalone/prebuild versions of the cli in:
See: https://github.com/balena-io/balena-cli/releases

This is a follow-up of:
See: https://github.com/balena-io/balena-cli/issues/1450

**Comment by jellybob** [comment]
This would be hugely appreciated - I'm attempting to build a Docker image containing the Balena CLI which needs to run on both x86 machines and Apple ARM devices. Because there are standalone ARM builds the Docker image build takes substantially longer than it would otherwise because I'm having to install Node + NPM, then compile all the dependencies for the Balena CLI.

**Comment by dfunckt** [comment]
Fixed #2744
