### ISSUE TITLE
Cannot pipe input to balena ssh

### ISSUE THREAD

**Issue by kb2ma** [balena-io/balena-cli#2681]
Input piped to the `balena ssh` command no longer is interpreted as such. 

# Expected Behavior
Below is behavior with v16.7.

```
$ echo "uptime; exit;" |balena ssh b95f308
=============================================================
    Welcome to balenaOS
=============================================================
 21:41:04  up 15 days  2:50,  0 users,  load average: 0.98, 0.99, 1.00
```

# Actual Behavior
Below is behavior with v17.1.4.
```
$ echo "uptime; exit;" |balena ssh b95f308
Could not find a container matching service name "uptime; exit;" on device "b95f308".
Available services:
	cloud-relay
	sensor
	otel-collector
	mqtt
	node-exporter
```

# Specifications

```
$ balena version -a
balena-cli version "17.1.4"
Node.js version "18.5.0"
```
Ubuntu 22.04

**Comment by otaviojacobi** [comment]
Hello @kb2ma thanks for reporting. This issue was introduced on 7.1.3 where we updated oclif from the old deprecated v1 to the latest @oclif/core package and got several advantages with it. However, one of the breaking changes from the upstream module is allowing arguments to be read from the standard in, which can be a nice feature for some cases but not for our ssh command. #2682 disables this behavior for the ssh command specifically so this should be working again once it is merged (probably version 17.1.5)

**Comment by otaviojacobi** [comment]
Hello @kb2ma can you confirm it also works for you with latest? It did for me

**Comment by kb2ma** [comment]
Works for me @otaviojacobi !
