### ISSUE TITLE
command signatures in help

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#357]
Been thinking that the command description in `resin help` (the overview) is still a bit too sparse and inconsistent, and how to improve on that. Some notes:
- `help [command...]`: why the `...`? I think only one command can be called.
- there are commands that have optional parameters that are listed as bare commands (`login`), while others are listed with one of the parameters highlighted (`sync [source]`).
- not obvious which commands have optional parameters to add (unless people go to the particular `resin help command` to read up)

I know that it's pretty simple at the moment for easy overview, still some kind of cue would be good, IMHO. Some examples that come to mind are either the type of help `curl` or `ssh` does on Linux. On one end just add `[options...]` where appropriate to signal that there's more to know:

```
$curl --help
Usage: curl [options...] <url>
...
```

Alternatively, `ssh` basically lists everything:

```
$ssh
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

So for example for `sync` the patterns would be one of the two following:
- `sync [options...]`
- `sync [-s path] [-i paths] [-b command] [-p] [-t port] [-v]`

As a user, I sort of wish it was the latter, but as a developer I know it might be too much info, so the former would work probably too. The worst is probably mixing the two style...

Any thoughts?

**Comment by jviotti** [comment]
Hi @imrehg ,

> `help [command...]`: why the `...`? I think only one command can be called.

The sparse modifier is required to be able to parse commands like `resin help app create`, since the actual command has more than one word. Sadly hiding the `...` might not be very straightforward since Capitano is built such that you can specify the command signature declaratively, and the same signature that gets parsed by Capitano is the one used in the help description.

Maybe we should re-consider single word commands to simplify things? E.g: `resin app-create` or `resin app:create` instead of `resin app create`? I'd personally like to keep the multiple word ones since it looks much more natural.

> there are commands that have optional parameters that are listed as bare commands (login), while others are listed with one of the parameters highlighted (sync [source]).

Not sure what you mean here. `resin login` doesn't take any parameter, while `resin sync [source]` takes an optional parameter, thus the difference in the way we show them.

> not obvious which commands have optional parameters to add (unless people go to the particular resin help command to read up)

I believe you're referring to command options, rather than parameters, which yeah, should be displayed in a better way :+1:

I like the idea of showing `[options...]` before the actual parameters for commands that do take options. I'd an awesome idea, and trivial to implement.

> As a user, I sort of wish it was the latter, but as a developer I know it might be too much info, so the former would work probably too. The worst is probably mixing the two style...

We can consider this. The commands don't have *that much* options, so I guess we can display them that way, which is again trivial.

The awesomeness if Capitano is that it allows you to register the commands and their options, but lets you create help pages the way you like giving the data structures it provides.

**Comment by imrehg** [comment]
I think we are pretty much on the same page, and thanks for illuminating a lot of things!

> > `help [command...]`: why the `...`? I think only one command can be called.
> 
> The sparse modifier is required to be able to parse commands like `resin help app create`, since the actual command has more than one word. Sadly hiding the `...` might not be very straightforward since Capitano is built such that you can specify the command signature declaratively, and the same signature that gets parsed by Capitano is the one used in the help description.

Ah, I actually glanced over the fact that there are commands with multiple words. Actually, there's only one, `app create`, others are all single word. Yeah, I think it's fine the way it is now.

> Maybe we should re-consider single word commands to simplify things? E.g: `resin app-create` or `resin app:create` instead of `resin app create`? I'd personally like to keep the multiple word ones since it looks much more natural.

Yeah, it looks some way more natural, though to me does not look particularly "linuxy" - but I admit that it wasn't the aim to be linuxy anyways (and it is just an opinion). :) So yeah, I think it's good to keep things like this for the time being, developer happiness is what make the project work well. Could always create an alias in the command if we really need to (e.g. renaming a command and keeping backwards compatibility for a while), right?

> I believe you're referring to command options, rather than parameters, which yeah, should be displayed in a better way :+1:

Yup, good catch. I used "options" & "parameters" interchangeably. Looking at this project a bit to read up on it, [docop - command-line interface description language](http://docopt.org/), as some external opinion and education. Now I get the `executable command option` description a lot clearer.

> I like the idea of showing `[options...]` before the actual parameters for commands that do take options. I'd an awesome idea, and trivial to implement.

Basically I think my impression comes down to the request to to have `resin help` show in a single glance which command has extra options and which does not. Also, the order in which is show in the help is important as they are not all interchangeable in their order (as you mentioned before) 

> > As a user, I sort of wish it was the latter, but as a developer I know it might be too much info, so the former would work probably too. The worst is probably mixing the two style...
> 
> We can consider this. The commands don't have *that much* options, so I guess we can display them that way, which is again trivial.

Been thinking about it, maybe best of both worlds: keep some kind of clear interface for `resin help` (the current one, with a couple of small improvements like above), and add the full list to `resin help --verbose`?

**Comment by jviotti** [comment]
> Ah, I actually glanced over the fact that there are commands with multiple words. Actually, there's only one, app create, others are all single word. Yeah, I think it's fine the way it is now.

Notice that we only show the most common commands in `resin help`, while showing all of them with `resin help -v`. There are many multiple word commands:

```
Additional commands:

    version                             output the version number
    logout                              logout from resin.io
    signup                              signup to resin.io
    whoami                              get current username and email address
    app rm <name>                       remove an application
    app restart <name>                  restart an application
    device rename <uuid> [newName]      rename a resin device
    device init                         initialise a device with resin os
    device rm <uuid>                    remove a device
    device identify <uuid>              identify a device with a UUID
    device reboot <uuid>                restart a device
    device register <application>       register a device
    device move <uuid>                  move a device to another application
    note <|note>                        set a device note
    keys                                list all ssh keys
    key add <name> [path]               add a SSH key to resin.io
    key <id>                            list a single ssh key
    key rm <id>                         remove a ssh key
    envs                                list all environment variables
    env add <key> [value]               add an environment variable
    env rename <id> <value>             rename an environment variable
    env rm <id>                         remove an environment variable
    os download <type>                  download an unconfigured os image
    os configure <image> <uuid>         configure an os image
    os initialize <image>               initialize an os image
    config read                         read a device configuration
    config write <key> <value>          write a device configuration
    config inject <file>                inject a device configuration file
    config reconfigure                  reconfigure a provisioned device
    config generate                     generate a config.json file
    settings                            print current settings
```

> Basically I think my impression comes down to the request to to have resin help show in a single glance which command has extra options and which does not. Also, the order in which is show in the help is important as they are not all interchangeable in their order (as you mentioned before)

I'm all for it. I'm going to send a PR soon.

> Been thinking about it, maybe best of both worlds: keep some kind of clear interface for resin help (the current one, with a couple of small improvements like above), and add the full list to resin help --verbose?

Yeah, that could work. In any case, displaying all the options will certainly cause the help output to horizontally overflow, but maybe we can change the `resin help` layout to include the command descriptions *below* the signatures?

**Comment by jviotti** [comment]
Regarding the `[options...]` additions, I just remembered we do something like this for the "usage" line already:

```
$ resin help
Usage: resin [COMMAND] [OPTIONS]
...
```

From the conversation above I suspect this is not enough? What do you think? Should we still add it to every command?

**Comment by imrehg** [comment]
I think your explanation as a whole makes sense. A lot of things are indeed right in front of me if I look and understand. Maybe the signal from this is that even if the info is there, people might miss it (assuming an average `Gergely`) but how to fix that is tough (without a Psychologist in Residence).

Based on this, it's probably better to:

* leave the things the way they are in the code, unless there's any more info or ideas picked up from this discussion and external feedback
* improve usability by writing a good guide/tutorial/how-to/examples section in our docs based on this discussion and more experimentation (I should do that anyways)

How's that?

**Comment by jviotti** [comment]
Haha, good guides are definitely a good thing, but I believe that if
there's a way to simplify the experience in a way that makes external
guides unnecessary we should try to go that way.

On Wed, Jun 29, 2016 at 06:47:11PM -0700, Gergely Imreh wrote:
> I think your explanation as a whole makes sense. A lot of things are indeed right in front of me if I look and understand. Maybe the signal from this is that even if the info is there, people might miss it (assuming an average `Gergely`) but how to fix that is tough (without a Psychologist in Residence).
> 
> Based on this, it's probably better to:
> 
> * leave the things the way they are in the code, unless there's any more info or ideas picked up from this discussion and external feedback
> * improve usability by writing a good guide/tutorial/how-to/examples section in our docs based on this discussion and more experimentation (I should do that anyways)
> 
> How's that?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/resin-cli/issues/357#issuecomment-229538430

-- 
Juan Cruz Viotti
Software Engineer, Resin.io

**Comment by lekkas** [comment]
@imrehg @jviotti what's your take on showing required options in the `resin help` command overview screen?

For example, `config read` requires a `--type <type>` option or it will throw an error. To be fair, the error message informs the user about the missing option, but then there is no way for a user to tell beforehand which options are required.

So for the particular command, the help message will change from

```bash
config read                               read a device configuration
```

to 

```bash
config read --type <type>                 read a device configuration
```

**Comment by jviotti** [comment]
@lekkas In UNIX, this usually take the form of `config read [--type <type>]`.

**Comment by lekkas** [comment]
@jviotti the above example represents required options, so it's in line with what you are saying on missing square brackets no?

The thing is that, in UNIX, options, being optional by definition, are usually optional and therefore represented in square brackets in `help` sections. But then, the form I propose is not perfect either because users might assume that the only available options are the required ones.

**Comment by jviotti** [comment]
@lekkas 

> the above example represents required options, so it's in line with what you are saying on missing square brackets no?

Right. See `tar` for another example showcasing both optional and required options:

```
tar {-r | -u} -f archive-file [options] [files | directories]
```

They use curly braces to denote optionally, but notice that `-f` is a required option.

I believe we're all in the same page, and this notation should make sense to users.

**Comment by lekkas** [comment]
What if Capitano also printed out the command's `help` section along with the error message? That way the user would get a second chance to inspect the command's usage and any required options can simply be marked as such in their `description`

**Comment by lekkas** [comment]
Yeah just to make it clear I totally agree with your comments, just thinking out in the open :)

**Comment by jviotti** [comment]
That'd be nice, and should be easy to implement.

**Comment by pdcastro** [comment]
It's been suggested for the CLI to be refactored to use [oclif](https://github.com/oclif/oclif) instead of [Capitano], I think the main argument being that oclif is more actively maintained. This may be mentioned in the 2019 roadmap for the CLI. I think @CameronDiver had a go at using oclif in another project and had some thoughts. If it did happen, the discussion in this issue would be very relevant.

**Comment by pdcastro** [comment]
The reason why I'm labelling this issue as high priority is that "appearances matter". This is the CLI equivalent of an ugly / sloppy website. We can have -- and we do! -- the most powerful and awesome IoT platform / backend behind the CLI, but if users run `balena help` and get an inconsistent / sloppy formatting of the commands, even if perfectly functional, it doesn't do justice to the platform.

**Comment by pdcastro** [comment]
It sounds like most of the suggestions in this issue meant modifying how Capitano summarises command usage, in particular the distinction between parameters and options, required vs optional. With the decision to migrate from Capitano to oclif, in part to reduce CLI framework development effort, I don't expect we will actually be making such modifications -- whether to Capitano or to oclif. Currently, most commands are still implemented in Capitano and the prevailing help format is Capitano's. PR #1506 (commit [b69ba0b](https://github.com/balena-io/balena-cli/pull/1506/commits/b69ba0b6170368d1178a94d8fdbc6e02c3ff8a87)) actually translates oclif's format to Capitano's in order to at least avoid exposing framework inconsistency -- e.g. Capitano highlights required parameters with angle brackets and lower case, whereas oclif highlights them with ALL CAPITALS and no brackets. When most commands are implemented in oclif instead of Capitano, we can adopt oclif's format instead.

As I don't see what remains specifically actionable in this issue, I am closing it. Feel to add a comment - the issue can of course be reopened!
