### ISSUE TITLE
Make the various sync/push/deploy commands consistent and clear

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#491]
See discussion around local builds here: https://github.com/resin-io/hq/pull/732#discussion_r111994981.

We currently have:

* `resin sync` - rsyncs files to a remote device
* `resin local push` - sometimes builds and deploys a container to a local device, sometimes rsyncs

We'll soon also have `resin deploy`, which will build and deploy containers to remote devices.

It's not clear from the names what the differences are between these, and it'd be nice if that were clearer, and these had obvious use cases and behaviour. One proposed option:

* `resin sync` - rsyncs files to a remote device via resin.io
* `resin deploy` - deploys a container (potentially building it first) to a remote device via resin.io
* `resin local sync` - rsyncs files to a local device
* `resin local deploy` - deploys a container (potentially building it first) to a local device

**Comment by brownjohnf** [comment]
Why not do:

```
resin sync
resin deploy
resin deploy --local
```

Or alternatively

```
resin local sync
resin local deploy
resin cloud sync
resin cloud deploy
```

**Comment by pimterry** [comment]
I marginally prefer the original syntax above, but I don't object to either of those as alternatives if others prefer them.

Definitely agree there's some interesting things we could do to improve the dev experience here with configurable (or even automatic?) local/cloud behaviour, but I think we should punt that as a separate issue to keep this focused for now.

**Comment by pimterry** [comment]
Also, if we did split these, would we still want to expose a way to get the intelligent sync behaviour somehow? If so, how would we like to do that? I don't get much value from that personally, but if we do want to keep it I can think of a few options:

* Have `resin local push` in addition to `local deploy` and `local sync` - push just checks the triggers and delegates to the appropriate other command.
* Add a flag to deploy (e.g. `local deploy --allow-sync`) which turns this on explicitly.

**Comment by pdcastro** [comment]
Related to #357 and #464

**Comment by pdcastro** [comment]
The `sync` and `local push` commands were removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the new `balena push` command.

Other than `balena push`:
* `balena build` builds an image using a local Docker daemon.
* `balena deploy` uploads a previously built Docker image to balenaCloud.

Perhaps just as importantly, we now have much better documentation than when this issue was created! -
* https://www.balena.io/docs/learn/deploy/deployment/
* https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/
