### ISSUE TITLE
resin local push: Add no-cache option

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#506]

**Comment by sako0938** [comment]
Is there a workaround for this? My workaround still requires messing around with the dockerfile in a minor way. Shouldn't ```resin local push -f``` do this?

**Comment by pimterry** [comment]
@sako0938 `-f` is used to force a Docker build, rather than a simple file sync, not to manage the build itself. This is a little confusing, and we do have plans to improve it, but not quite yet.

The simplest workaround in the short term I think is to clear the Docker images on the device manually. Development devices directly expose the Docker API on port 2375, so if you set `DOCKER_HOST` to point to your device (e.g. `tcp://1.2.3.4:2375`) then you can use the Docker client with it directly.

`docker images -a` should show every image on the device, for example, and `docker system prune` should clear all build cache (and more) for you.

**Comment by pdcastro** [comment]
The `local push` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. And it does support a `--nocache` option!
