### ISSUE TITLE
resin sync does not work with passphrase protected ssh keys

### ISSUE THREAD

**Issue by michal-mazurek** [balena-io/balena-cli#526]
"resin sync" never worked for me, until i figured out i need to start an ssh-agent beforehand. my ssh key is protected with a passphrase. there was no user feedback suggesting that

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1o8j)

**Comment by curcuz** [comment]
@imrehg @michal-mazurek the title of this issue might be misleading, if my understanding that the actual issue is a lack of documentation around the need of having ssh-agent up and loaded - am I correct?

**Comment by imrehg** [comment]
well, if the password request never pops up, then it would be hard to debug for people. Documentation helps, but the error message should do the main documentation? Otherwise resin-cli does a lot of interactive stuff asking for input from user, I wonder why it couldn't ask for the password. Just thinking out loud.

**Comment by curcuz** [comment]
@imrehg good point.

**Comment by pdcastro** [comment]
The `sync` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. See also: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
