### ISSUE TITLE
Git for Windows does not seem to come with rsync

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#527]
In the docs it is suggested to use for example Git for Windows. Tested the current (2.13.0) version, and `bash` in that does not seem to have `rsync` that is required for `resin sync`, and thus sync does not work. These Windows instructions might need update and/or clarification? (used on Windows 10).

**Comment by flesler** [comment]
In case you want to use the link or copy the instructions, I followed [this guide](https://alanbarber.com/2015/08/11/installing-rsync-on-windows/) to add `rsync` to Git for Windows.

Worth mentioning `resin sync` is not working for me atm but I think it's my fault due to where I placed the shared libraries

**Comment by pdcastro** [comment]
The `sync` command and its `rsync` dependency were removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command.

Also, earlier this year the installation instructions for Windows were significantly improved:
https://github.com/balena-io/balena-cli/blob/master/INSTALL.md
