### ISSUE TITLE
CLI commands do not indicate if a device BSP is discontinued

### ISSUE THREAD

**Issue by willnewton** [balena-io/balena-cli#585]
As part of https://github.com/resin-io/hq/pull/785 a number of previously supported devices have been deprecated. The CLI commands, e.g. ```devices supported``` and probably ```app create``` should output a message indicating that a discontinued BSP is being used. There is also an "experimental" state that also could be exposed if that is useful.

**Comment by lekkas** [comment]
See: https://github.com/resin-io/hq/pull/785

**Comment by willnewton** [comment]
BSP = Board Support Package btw.

**Comment by pimterry** [comment]
`app create` will stop allowing creation of discontinued apps as soon as we update to SDK v7, which is slowly but steadily in progress.

`devices supported` does right now have markers for discontinued devices, on my machine it outputs:

```
➜ resin devices supported                      
SLUG                  NAME
...
beaglebone-green      BeagleBone Green (BETA)
colibri-imx6dl        Colibri iMX6dl (BETA)
cybertan-ze250        Cybertan ZE250 (ALPHA)
edge                  Edge Device Builder (DISCONTINUED)
generic-amd64         Generic amd64
generic               Generic
hummingboard          Hummingboard
imx6ul-var-dart       Variscite DART-6UL (BETA)
intel-edison          Intel Edison
...
```

This only works because the name in the device type itself has that suffix appended though, we're not doing anything clever.

@willnewton is that going to be the case for future discontinued devices? If so, we don't need to do anything for that. If not, we need to add some logic to add this from the device type state and add it to the name, handling the `edge` case where it's already been embedded there (or updating that device type to remove it).

**Comment by pdcastro** [comment]
Closing this issue as I believe it was recently addressed (or is no longer applicable) as part of issue #1485 and PR #1501. The discontinued devices are no longer listed at all. Feel free to add a comment if you think this issue should not have been closed -- happy to reopen it as needed, or create a new one.
