### ISSUE TITLE
resin local push should support all types of buildable projects (e.g. dockerfile.template)

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-cli#604]
The resin local push should support the same types of projects as the builder and `resin deploy`

**Comment by pdcastro** [comment]
I understand this issue was fixed / implemented. Also, the `local push` command was removed in CLI v11, replaced with the ["live push" feature](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/) which is enabled by default with the `balena push <ip-address>` command. See also: [Deploy to your Fleet](https://www.balena.io/docs/learn/deploy/deployment/) documentation.
