### ISSUE TITLE
Improve CLI experience on slow/unreliable networks

### ISSUE THREAD

**Issue by pimterry** [balena-io/balena-cli#671]
This is useful for all our users, but likely particularly useful for large hackathons, which where the internet can be unstable and is often slow. The CLI should be as resilient as possible under these circumstances, should fail fast when things are broken, and should provide good feedback on what's going on if things are going slowly.

https://wiki.linuxfoundation.org/networking/netem#examples has some good examples of how to emulate slow/unreliable networks on linux.

**Comment by pdcastro** [comment]
A significant improvement in this area, though limited to the `balena deploy` command, was introduced by pull request #1057 
Other pull requests have addressed error conditions since this issue was originally raised.
I am closing this issue because it is arguably too open ended. More specific improvement suggestions will always be welcome.
