### ISSUE TITLE
resin local flash doesn't understand zipped images

### ISSUE THREAD

**Issue by willnewton** [balena-io/balena-cli#692]
- **resin-cli version:**

6.7.0

- **Operating system and architecture:**

Linux/x86_64

```resin local flash img.zip``` results in a very fast flash which looks like it is just flashing the zip file verbatim to the SD card. It would be nice if it could detect the zip file and extract it as I believe etcher does.

**Comment by lurch** [comment]
Does this use the etcher-image-write stuff? I can't remember which part of Etcher does the unzipping, but it feels like this has definite overlaps with the Etcher CLI... (ping @jviotti and @jhermsmeier )

**Comment by jhermsmeier** [comment]
Etcher uses [thejoshwolfe/yauzl](https://github.com/thejoshwolfe/yauzl) for streaming from .zip archives, and the archive / compression handlers are in Etcher itself, not `etcher-image-write` (which will be deprecated soon-ish, once https://github.com/resin-io/etcher/pull/1671 lands).

**Comment by lurch** [comment]
Ahhh. So I guess resin-cli will need to start making use of the upcoming Etcher SDK instead?

**Comment by pimterry** [comment]
@jhermsmeier @lurch what's the timeline on the Etcher SDK? It'd be great to move the CLI to use that as soon as we can once `etcher-image-write` is deprecated, especially if it would magically solve this issue (which sounds likely) since all dashboard image downloads are now in zip format.

Presumably the Etcher SDK will also do image validation, which would be nice - even if we don't support zips, we should definitely be throwing an error rather than writing a gibberish over the SD.

**Comment by pdcastro** [comment]
@zvin, has your recent pull request (https://github.com/balena-io/balena-cli/pull/1052) addressed this issue?
(But probably not issue #496, right?)

**Comment by zvin** [comment]
#1052 should be a very small change, I'll PR it quickly.
