### ISSUE TITLE
Update Notifier feature can result in ' Error: EACCES: permission denied, mkdir '/.config' errors

### ISSUE THREAD

**Issue by lekkas** [balena-io/balena-cli#693]
- **resin-cli version:** 6.7.0
- **Operating system and architecture:** Ubuntu 16.04 base image

Possibly related snippets:

https://github.com/resin-io/resin-cli/blob/0b26fda89cdbf262c841b0753d3b8064b8c5514c/lib/utils/update.coffee#L25-L31

Also see https://www.npmjs.com/package/update-notifier#user-settings

**Comment by pimterry** [comment]
We should make update notifier use `RESINRC_DATA_DIRECTORY` correctly, and make the CLI resilient to any update notifier errors too, so we ignore any kind of failures here (while still reporting them to sentry).

**Comment by pimterry** [comment]
With #698 solved this is now much lower priority: these failures no longer break the CLI, and the update notifier can be disabled entirely with `NO_UPDATE_NOTIFIER`.

We should still fix this to obey RESINRC_DATA_DIRECTORY, so that users with non-writable `~/.config` still get update notifications, but I'll drop the priority.

**Comment by pdcastro** [comment]
Closing this issue in favour of #1667 and #1669, and also because update-notifier has had a couple of major-version updates (now at 4.1.0) since this issue was created.
