### ISSUE TITLE
resin sync should ignore files listed in .dockerignore

### ISSUE THREAD

**Issue by zvin** [balena-io/balena-cli#745]
Like we did for `.gitignore` in https://github.com/resin-io/resin-cli/pull/367 .
The user requesting this feature also suggests that we could have a specific `.resinignore` file for that purpose.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5v89)

**Comment by pimterry** [comment]
Imo this should just be `.dockerignore`, not a separate file. That should make it easier to keep `resin sync` behaviour fairly consistent with docker build behaviour.

I've put this in as low priority, since there's a manageable (if slightly awkward in some cases) workaround available by using `.gitignore` instead.

**Comment by pdcastro** [comment]
Related to issues #889 and #1032

**Comment by pdcastro** [comment]
Closing this issue because the `sync` command was removed in CLI v11.
