### ISSUE TITLE
resin sync has no 'source' attribute in .resin-sync.yml

### ISSUE THREAD

**Issue by brittohalloran** [balena-io/balena-cli#746]
Using `sudo resin sync -s ./app -d /usr/src/app` works great and creates a `.resin-sync.yml` file.

The next time, I expected to be able to simply `sudo resin sync`, but it puts the contents of the current (wrong) folder into `/usr/src/app`. I then noticed that there was no `source: <path>` field in `.resin-sync.yml`. Manually adding it (relative or absolute path) does nothing. 

Is this the intended behavior? Any reason it can't use a `source: ` path in `.resin-sync.yml`?

**Comment by thgreasi** [comment]
Hi @brittohalloran,
It's true that as of the current implementation there is no `source` option in the generated `.resin-sync.yml` and the current working directory is assumed.
For now, in order to have `resin sync` work w/o any additional option at all & just relying to the `.resin-sync.yml`, you will have to `cd` into your pepo's directory before the initial `resin sync` command.

For now, if you need to run `resin sync` from an other directory, then your subsequent resin-sync commands will have to pass the source path of the repo `resin sync -s ./app`.

That's an reasonable request though, thanks for reporting.

**Comment by msegado** [comment]
I'd recommend adding the current behavior to the docs in the meantime - currently they don't mention `source` and `destination` being treated differently.

Thanks for the great project!

**Comment by pdcastro** [comment]
Closing this issue because the `sync` command was removed in CLI v11, replaced with the "[live push](https://www.balena.io/blog/living-on-the-edge-with-livepush-and-other-cli-improvements/)" feature which is enabled by default with the `balena push <ip-address>` command.
