### ISSUE TITLE
emulated builds on windows

### ISSUE THREAD

**Issue by ashirley** [balena-io/balena-cli#749]
- **resin-cli version:** 6.12.1 (and HEAD)
- **Operating system and architecture:** Windows x64

I have been trying to run an emulated build from windows. I have raised issue 748 on a related but orthogonal matter. There are 2 remaining issues. The first is that qemu is copied into the container but is not executable. The easiest solution to this is to always add it to the tar ball with 777 permissions. I am happy to either include this in 748 or raise a separate PR for it.

The other thing is the platformNeedsQemu function which means we only try to actually do any emulation on linux. I'm not sure what the intention of this function is but if it returns false, -e doesn't do anything except a console.log. 

I can either remove it entirely or change it to be based on `process.arch` so that we don't try to emulate if we are already running on the target architecture (although arguably, it is the user's responsibility to provide -e only when they mean it?), which ever you'd prefer. Again I can either roll this into 748 or put it in a separate PR.

Let me know what you'd prefer and I'll prepare a PR.

**Comment by pimterry** [comment]
`platformNeedsQemu` returns false for windows mainly because emulation hasn't been tested on Windows, and we simply have no idea if it'll work (most of our developers, customers & users are on Linux or Mac). I'd love to add Windows support though, and I'm very happy if you're in a place to do that investigation and open some PRs to get it going!

I'd rather we keep PRs separate, and leave #748 as-is, but I'd love PRs making the improvements you're talking about, if you've tested them and you've got full emulation working for you locally.

Some context by the way: with #673 we're eventually aiming towards making this argument unnecessary, and turning emulation on or off automatically (maybe removing the arg entirely) based on the local platform and target architecture. I'm not sure what the Windows situation will be, but it does need to take the local platform into consideration, as the qemu setup isn't required on OSX.

**Comment by ashirley** [comment]
Raised  #750 for adjusting the file permissions. Changes to `platformNeedsQemu` still remaining

**Comment by pdcastro** [comment]
I believe this issue was fixed in CLI v11.14.2 (currently 11.18.3), PR #1464. I have successfully tested emulated builds on Windows 10 (using Docker for Windows 18.06.1). If you find that the issue hasn't been fixed, just add a comment and I'll be happy to reopen it and investigate further.
