### ISSUE TITLE
Command failed: /usr/sbin/diskutil unmountDisk force

### ISSUE THREAD

**Issue by ruudboon** [balena-io/balena-cli#756]
After successfully writing the SD in MacOS High Sierra I see the following message.
```
1: Command failed: /usr/sbin/diskutil unmountDisk force "/dev/disk3"
Forced unmount of disk3 failed: at least one volume could not be unmounted
``` 
Ejecting in the finder works fine.

**Comment by pimterry** [comment]
This can happen for a few reasons, but I think it's most likely that there's something else looking at the disk at the moment we try to eject it.

Can you reliably reproduce this? If so, can you try running the command above (with `sudo`) and seeing if just retrying works? If it doesn't, try `sudo lsof | grep disk3`, which should tell you if there's another process using the disk. If retrying does help then we can easily make the CLI do that automatically.

**Comment by lurch** [comment]
ISTR we also had "some issues" with unmounting disks on macOS on Etcher? @jhermsmeier or @jviotti might remember more details...

**Comment by jhermsmeier** [comment]
Yeah, I remember it was a combination of time & retries on Mac OS – but that might have been specific to the C APIs.

**Comment by ruudboon** [comment]
@pimterry I will give it some extra testing this weekend.

**Comment by pdcastro** [comment]
Was this about the `balena local flash` command? It was recently rewritten to use the `etcher-sdk` (pull request #1052). I have tested it on MacOS 10.14.2 (Mojave) and had no problems. If there is still an issue, chances are it's an issue for the [etcher-sdk repo](https://github.com/balena-io-modules/etcher-sdk) rather than `balena-cli`, so I'm now closing this issue. Feel free to reopen as needed.
