### ISSUE TITLE
Update docs to reflect MC support

### ISSUE THREAD

**Issue by zwalchuk** [balena-io/balena-cli#806]
Include information on what features are supported by what versions of the CLI, specifically around multicontainer support (`resin deploy` supports multicontainer on v7.0.x and greater, for example)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9x6h)

**Comment by pdcastro** [comment]
From the Front conversation, I see that the motivation for this issue was to help balena support agents to be able to reply to users that a certain feature or bug fix was delivered in "CLI version x.y.z".  The closest we get to this at the moment is the [CHANGELOG](https://github.com/balena-io/balena-cli/blob/master/CHANGELOG.md) file. An additional document, or perhaps a table in the README file, to keep track of features and CLI versions would be an additional "source of truth" that could get outdated, and would need effort to be kept in sync with the codebase. Also, there is rarely reason to recommend older versions of the CLI, and features like multicontainer support are always be "better" in the latest versions. So if a user is looking for multicontainer support for a CLI command, the best best is always to use the latest version.

For these reasons, I am inclined to close this issue. I am however open to be persuaded :-) of the benefits of such additional documentation, so just leave a comment if you don't quite agree with my reasoning. No worries! :-)
