### ISSUE TITLE
resin os configure hangs

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#917]
Trying to use `os configure` with the latest available version for the Pi3, but it seems to hang and never finish:
```
$ resin os configure /tmp/resin-testpi3-raspberrypi3-2.12.7+rev1-dev-v7.4.3.img --device b5097e1b852b0be44b9245d286e2f4e3
Configuring operating system image
? Network Connection wifi
? Wifi SSID esting
? Wifi Passphrase *************
/etc/os-release: Unknown code ext2 76 
```
and it just hands there. No process seems to be going on (according to `ps`). With a few `CTLR-C` can exit.

- **resin-cli version:** v7.6.2
- **Operating system and architecture:** ArchLinux 64bit

**Comment by pimterry** [comment]
@imrehg I've tested this and tried to reproduce, but I can't. I suspect something awry within node-ext2fs, since we've had trouble with that before, and with it on Arch in particular.

Can you still reproduce this reliably now? There's been a few ext2fs changes & fixes recently, so perhaps something has changed. If you're still hitting this though, I'm not really sure how to investigate further, I think we'll need @zvin's help.

**Comment by pdcastro** [comment]
Possibly related to #998. However, a lot has changed since then, e.g. PR #1507 / CLI v11.18.0, plus the introduction of the `npm-shrinwrap.json` file to better control dependency versions in the npm installation. I cannot reproduce the issue. Well, I was also using newer balenaOS images, like 2.32 and 2.44.
