### ISSUE TITLE
resin local ssh fails with full UUID, succeeds with 7 character UUID

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [balena-io/balena-cli#973]
- **resin-cli version:** 7.10.4
- **Operating system and architecture:** macOS 10.13.6 High Sierra (darwin x64)

As reported in issue #940 `resin local scan` sometimes fails, which means that `resin local ssh` also will fail unless you provide the UUID or IP address. The first is available from the resin dashboard as a 33 character UUID. Unfortunately the resin-cli cannot use the entire UUID as provided by the resin dashboard:
>$ sudo resin local ssh dd736927d095a372a83e3f124bc21e11.local
>ECONNRESET: socket hang up

However the resin CLI succeeds when using only the first 7 characters:
> $ sudo resin local ssh dd73692.local

Or when using the IP address:
> $ sudo resin local ssh 10.168.50.105

Note that arp-scan can also be used to find devices on the local network.

**Comment by pimterry** [comment]
@drjasonharrison-vp-eio thanks for the issue, this is a good point.

@CameronDiver @hedss this is interesting. Independently we still need to fix the linked issue, but I can see how it'd also make sense and be very convenient if the device was available on both the 7 character and full length UUIDs. Is there a reason we can't broadcast both?

**Comment by hedss** [comment]
@pimterry Yes, this is because Avahi simply uses the current hostname for DNS-SD broadcast.

In theory, I think we could do this by just adding a PTR record to the service being returned, as the reverse lookup should be able to point to the shortened service. In practice, I think this is problematic as I don't believe Avahi lets you do this. We could add another service, but again I think Avahi would spot the same service running on the same port and stop you from doing it. It needs some thought.

**Comment by drjasonharrison-vp-eio** [comment]
Another option is for the resin cli to truncate the host name to the first seven characters. I started with the full UUID by copying it from the dashboard.

**Comment by pimterry** [comment]
Hmm, that's an interesting idea. We can't blindly truncate immediately when given a host (you might not be passing a UUID, but some other long hostname that resolves to your device), but we could work around that. E.g. we could check if you've passed a hostname with a standard UUID length, and if so query the API to check if the given UUID exists, and if so truncate it and use the short version.

It feels a little messy, but I can definitely see how that'd be useful, and since UUIDs are unique by definition if we get a match from the API we can be very confident indeed that that's what you're trying to do.

**Comment by pdcastro** [comment]
It looks like this issue was "fixed" (or became obsolete) with the new implementation of `balena ssh` in CLI v11, which accepts both full and short UUIDs, IP addresses or `".local"` domain names, and also allows ssh'ing directly into application containers/services. The `balena local ssh` variant was removed. As of v11.18.2:
```
$ balena help ssh
Usage: ssh <applicationOrDevice> [serviceName]

This command can be used to start a shell on a local or remote device.

If a service name is not provided, a shell will be opened on the host OS.

If an application name is provided, all online devices in the application
will be presented, and the chosen device will then have a shell opened on
in it's service container or host OS.

For local devices, the IP address and .local domain name are supported.
If the device is referenced by IP or `.local` address, the connection
is initiated directly to balenaOS on port `22222` via an
openssh-compatible client. Otherwise, any connection initiated remotely
traverses the balenaCloud VPN.

Examples:
	balena ssh MyApp

	balena ssh f49cefd
	balena ssh f49cefd my-service
	balena ssh f49cefd --port <port>

	balena ssh 192.168.0.1 --verbose
	balena ssh f49cefd.local my-service

Warning: `balena ssh` requires an openssh-compatible client to be correctly
installed in your shell environment. For more information (including Windows
support) please check:
	https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#additional-dependencies

Options:

    --noproxy                           Don't use the proxy configuration for this connection. This flag only make sense if you've configured a proxy globally.
    --port, -p <port>                   SSH gateway port
    --verbose, -v                       Increase verbosity
```
