### ISSUE TITLE
CLI is not returning success exitcode (0) when command not recognised.

### ISSUE THREAD

**Issue by Atiklabsl** [balena-io/balena-cli#983]
- **resin-cli version: v7.10.6**
- **Operating system and architecture: Windows 7 x64**

`resin someunknowcommand`

results in exit code 0 (success).   

This could cause issues with automated uses of the cli, and also potentially in other parts of the cli that use `capitano.run`.

**Comment by pdcastro** [comment]
It looks like this issue was fixed in CLI release v11.17.5 (PR #1506, commit [74a521a](https://github.com/balena-io/balena-cli/pull/1506/commits/74a521a271f53da218d8494bf16a457cfa6c076f)).

@nwneisen, your comment fell through the cracks and was not replied to, sorry! There are more issues labeled "good first issue" and "low-hanging-fruit" if you'd like to help with the CLI project, which is much appreciated. 👍  Check also the [CONTRIBUTING](https://github.com/balena-io/balena-cli/blob/master/CONTRIBUTING.md) file -- there isn't that much in there, but we can expand it with your feedback, and/or you could add to it as well. :-)  We can guide you further if you add comments to the issues you choose to work on, and/or create a PR. (We will reply to your comment next time!)
